// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.r3.sgx.proto.host;

public interface OcallOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ocall)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool is_request = 1;</code>
   */
  boolean hasIsRequest();
  /**
   * <code>optional bool is_request = 1;</code>
   */
  boolean getIsRequest();

  /**
   * <code>optional bytes bytes = 2;</code>
   */
  boolean hasBytes();
  /**
   * <code>optional bytes bytes = 2;</code>
   */
  com.google.protobuf.ByteString getBytes();
}
