// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.r3.sgx.proto.host;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ecall_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ecall_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ocall_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ocall_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\"*\n\005Ecall\022\022\n\nis_request\030\001 \001(" +
      "\010\022\r\n\005bytes\030\002 \001(\014\"*\n\005Ocall\022\022\n\nis_request\030" +
      "\001 \001(\010\022\r\n\005bytes\030\002 \001(\014B%\n\025com.r3.sgx.proto" +
      ".hostB\004TestP\001\242\002\003HLW"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Ecall_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Ecall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ecall_descriptor,
        new java.lang.String[] { "IsRequest", "Bytes", });
    internal_static_Ocall_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Ocall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ocall_descriptor,
        new java.lang.String[] { "IsRequest", "Bytes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
