// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.r3.sgx.enclave.example;

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExampleEcall_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExampleEcall_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExampleOcall_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExampleOcall_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\"\037\n\014ExampleEcall\022\017\n\007messa" +
      "ge\030\001 \002(\t\"\037\n\014ExampleOcall\022\017\n\007message\030\002 \002(" +
      "\tB-\n\032com.r3.sgx.enclave.exampleB\007Example" +
      "P\001\242\002\003HLW"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ExampleEcall_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ExampleEcall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExampleEcall_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_ExampleOcall_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ExampleOcall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExampleOcall_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
