// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.r3.sgx.enclave.example;

public interface ExampleOcallOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExampleOcall)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string message = 2;</code>
   */
  boolean hasMessage();
  /**
   * <code>required string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>required string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
