// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enclavelet-host.proto

package com.r3.sgx.enclavelethost.grpc;

public interface ClientMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ClientMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required bytes blob = 1;</code>
   */
  boolean hasBlob();
  /**
   * <code>required bytes blob = 1;</code>
   */
  com.google.protobuf.ByteString getBlob();
}
