// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enclavelet-host.proto

package com.r3.sgx.enclavelethost.grpc;

public final class EnclaveletHostApi {
  private EnclaveletHostApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetEpidAttestationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetEpidAttestationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetEpidAttestationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetEpidAttestationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ClientMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ClientMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ServerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ServerMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_EpidAttestation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_EpidAttestation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025enclavelet-host.proto\022\005proto\"\033\n\031GetEpi" +
      "dAttestationRequest\"I\n\032GetEpidAttestatio" +
      "nResponse\022+\n\013attestation\030\001 \002(\0132\026.proto.E" +
      "pidAttestation\"\035\n\rClientMessage\022\014\n\004blob\030" +
      "\001 \002(\014\"\035\n\rServerMessage\022\014\n\004blob\030\001 \002(\014\"G\n\017" +
      "EpidAttestation\022\016\n\006report\030\001 \002(\014\022\021\n\tsigna" +
      "ture\030\002 \002(\014\022\021\n\tcert_path\030\003 \002(\0142\252\001\n\016Enclav" +
      "eletHost\022Y\n\022GetEpidAttestation\022 .proto.G" +
      "etEpidAttestationRequest\032!.proto.GetEpid" +
      "AttestationResponse\022=\n\013OpenSession\022\024.pro" +
      "to.ClientMessage\032\024.proto.ServerMessage(\001" +
      "0\001B;\n\036com.r3.sgx.enclavelethost.grpcB\021En" +
      "claveletHostApiP\001\242\002\003HLW"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_GetEpidAttestationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_GetEpidAttestationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetEpidAttestationRequest_descriptor,
        new java.lang.String[] { });
    internal_static_proto_GetEpidAttestationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_GetEpidAttestationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetEpidAttestationResponse_descriptor,
        new java.lang.String[] { "Attestation", });
    internal_static_proto_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ClientMessage_descriptor,
        new java.lang.String[] { "Blob", });
    internal_static_proto_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ServerMessage_descriptor,
        new java.lang.String[] { "Blob", });
    internal_static_proto_EpidAttestation_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_EpidAttestation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_EpidAttestation_descriptor,
        new java.lang.String[] { "Report", "Signature", "CertPath", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
