// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enclavelet-host.proto

package com.r3.sgx.enclavelethost.grpc;

public final class EnclaveletHostApi {
  private EnclaveletHostApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetEpidAttestationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetEpidAttestationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetEpidAttestationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetEpidAttestationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ClientMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ClientMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ServerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ServerMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_EpidAttestation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_EpidAttestation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025enclavelet-host.proto\022\005proto\"\033\n\031GetEpi" +
      "dAttestationRequest\"I\n\032GetEpidAttestatio" +
      "nResponse\022+\n\013attestation\030\001 \002(\0132\026.proto.E" +
      "pidAttestation\"\035\n\rClientMessage\022\014\n\004blob\030" +
      "\001 \002(\014\"\035\n\rServerMessage\022\014\n\004blob\030\001 \002(\014\"W\n\017" +
      "EpidAttestation\022\024\n\014ias_response\030\001 \002(\014\022\027\n" +
      "\017ias_certificate\030\002 \002(\t\022\025\n\rias_signature\030" +
      "\003 \002(\0142\252\001\n\016EnclaveletHost\022Y\n\022GetEpidAttes" +
      "tation\022 .proto.GetEpidAttestationRequest" +
      "\032!.proto.GetEpidAttestationResponse\022=\n\013O" +
      "penSession\022\024.proto.ClientMessage\032\024.proto" +
      ".ServerMessage(\0010\001B;\n\036com.r3.sgx.enclave" +
      "lethost.grpcB\021EnclaveletHostApiP\001\242\002\003HLW"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_GetEpidAttestationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_GetEpidAttestationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetEpidAttestationRequest_descriptor,
        new java.lang.String[] { });
    internal_static_proto_GetEpidAttestationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_GetEpidAttestationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetEpidAttestationResponse_descriptor,
        new java.lang.String[] { "Attestation", });
    internal_static_proto_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ClientMessage_descriptor,
        new java.lang.String[] { "Blob", });
    internal_static_proto_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ServerMessage_descriptor,
        new java.lang.String[] { "Blob", });
    internal_static_proto_EpidAttestation_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_EpidAttestation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_EpidAttestation_descriptor,
        new java.lang.String[] { "IasResponse", "IasCertificate", "IasSignature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
