// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enclavelet-host.proto

package com.r3.sgx.enclavelethost.grpc;

public interface EpidAttestationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.EpidAttestation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required bytes ias_response = 1;</code>
   */
  boolean hasIasResponse();
  /**
   * <code>required bytes ias_response = 1;</code>
   */
  com.google.protobuf.ByteString getIasResponse();

  /**
   * <code>required string ias_certificate = 2;</code>
   */
  boolean hasIasCertificate();
  /**
   * <code>required string ias_certificate = 2;</code>
   */
  java.lang.String getIasCertificate();
  /**
   * <code>required string ias_certificate = 2;</code>
   */
  com.google.protobuf.ByteString
      getIasCertificateBytes();

  /**
   * <code>required bytes ias_signature = 3;</code>
   */
  boolean hasIasSignature();
  /**
   * <code>required bytes ias_signature = 3;</code>
   */
  com.google.protobuf.ByteString getIasSignature();
}
