// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enclavelet-host.proto

package com.r3.sgx.enclavelethost.grpc;

/**
 * Protobuf type {@code proto.GetEpidAttestationResponse}
 */
public  final class GetEpidAttestationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.GetEpidAttestationResponse)
    GetEpidAttestationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetEpidAttestationResponse.newBuilder() to construct.
  private GetEpidAttestationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetEpidAttestationResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetEpidAttestationResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.r3.sgx.enclavelethost.grpc.EpidAttestation.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = attestation_.toBuilder();
            }
            attestation_ = input.readMessage(com.r3.sgx.enclavelethost.grpc.EpidAttestation.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(attestation_);
              attestation_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.r3.sgx.enclavelethost.grpc.EnclaveletHostApi.internal_static_proto_GetEpidAttestationResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.r3.sgx.enclavelethost.grpc.EnclaveletHostApi.internal_static_proto_GetEpidAttestationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse.class, com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ATTESTATION_FIELD_NUMBER = 1;
  private com.r3.sgx.enclavelethost.grpc.EpidAttestation attestation_;
  /**
   * <code>required .proto.EpidAttestation attestation = 1;</code>
   */
  public boolean hasAttestation() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .proto.EpidAttestation attestation = 1;</code>
   */
  public com.r3.sgx.enclavelethost.grpc.EpidAttestation getAttestation() {
    return attestation_ == null ? com.r3.sgx.enclavelethost.grpc.EpidAttestation.getDefaultInstance() : attestation_;
  }
  /**
   * <code>required .proto.EpidAttestation attestation = 1;</code>
   */
  public com.r3.sgx.enclavelethost.grpc.EpidAttestationOrBuilder getAttestationOrBuilder() {
    return attestation_ == null ? com.r3.sgx.enclavelethost.grpc.EpidAttestation.getDefaultInstance() : attestation_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasAttestation()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getAttestation().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, getAttestation());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAttestation());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse)) {
      return super.equals(obj);
    }
    com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse other = (com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse) obj;

    boolean result = true;
    result = result && (hasAttestation() == other.hasAttestation());
    if (hasAttestation()) {
      result = result && getAttestation()
          .equals(other.getAttestation());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAttestation()) {
      hash = (37 * hash) + ATTESTATION_FIELD_NUMBER;
      hash = (53 * hash) + getAttestation().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.GetEpidAttestationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.GetEpidAttestationResponse)
      com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.r3.sgx.enclavelethost.grpc.EnclaveletHostApi.internal_static_proto_GetEpidAttestationResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.r3.sgx.enclavelethost.grpc.EnclaveletHostApi.internal_static_proto_GetEpidAttestationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse.class, com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse.Builder.class);
    }

    // Construct using com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAttestationFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (attestationBuilder_ == null) {
        attestation_ = null;
      } else {
        attestationBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.r3.sgx.enclavelethost.grpc.EnclaveletHostApi.internal_static_proto_GetEpidAttestationResponse_descriptor;
    }

    public com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse getDefaultInstanceForType() {
      return com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse.getDefaultInstance();
    }

    public com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse build() {
      com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse buildPartial() {
      com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse result = new com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (attestationBuilder_ == null) {
        result.attestation_ = attestation_;
      } else {
        result.attestation_ = attestationBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse) {
        return mergeFrom((com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse other) {
      if (other == com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse.getDefaultInstance()) return this;
      if (other.hasAttestation()) {
        mergeAttestation(other.getAttestation());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasAttestation()) {
        return false;
      }
      if (!getAttestation().isInitialized()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.r3.sgx.enclavelethost.grpc.EpidAttestation attestation_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.r3.sgx.enclavelethost.grpc.EpidAttestation, com.r3.sgx.enclavelethost.grpc.EpidAttestation.Builder, com.r3.sgx.enclavelethost.grpc.EpidAttestationOrBuilder> attestationBuilder_;
    /**
     * <code>required .proto.EpidAttestation attestation = 1;</code>
     */
    public boolean hasAttestation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .proto.EpidAttestation attestation = 1;</code>
     */
    public com.r3.sgx.enclavelethost.grpc.EpidAttestation getAttestation() {
      if (attestationBuilder_ == null) {
        return attestation_ == null ? com.r3.sgx.enclavelethost.grpc.EpidAttestation.getDefaultInstance() : attestation_;
      } else {
        return attestationBuilder_.getMessage();
      }
    }
    /**
     * <code>required .proto.EpidAttestation attestation = 1;</code>
     */
    public Builder setAttestation(com.r3.sgx.enclavelethost.grpc.EpidAttestation value) {
      if (attestationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        attestation_ = value;
        onChanged();
      } else {
        attestationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .proto.EpidAttestation attestation = 1;</code>
     */
    public Builder setAttestation(
        com.r3.sgx.enclavelethost.grpc.EpidAttestation.Builder builderForValue) {
      if (attestationBuilder_ == null) {
        attestation_ = builderForValue.build();
        onChanged();
      } else {
        attestationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .proto.EpidAttestation attestation = 1;</code>
     */
    public Builder mergeAttestation(com.r3.sgx.enclavelethost.grpc.EpidAttestation value) {
      if (attestationBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            attestation_ != null &&
            attestation_ != com.r3.sgx.enclavelethost.grpc.EpidAttestation.getDefaultInstance()) {
          attestation_ =
            com.r3.sgx.enclavelethost.grpc.EpidAttestation.newBuilder(attestation_).mergeFrom(value).buildPartial();
        } else {
          attestation_ = value;
        }
        onChanged();
      } else {
        attestationBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .proto.EpidAttestation attestation = 1;</code>
     */
    public Builder clearAttestation() {
      if (attestationBuilder_ == null) {
        attestation_ = null;
        onChanged();
      } else {
        attestationBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .proto.EpidAttestation attestation = 1;</code>
     */
    public com.r3.sgx.enclavelethost.grpc.EpidAttestation.Builder getAttestationBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getAttestationFieldBuilder().getBuilder();
    }
    /**
     * <code>required .proto.EpidAttestation attestation = 1;</code>
     */
    public com.r3.sgx.enclavelethost.grpc.EpidAttestationOrBuilder getAttestationOrBuilder() {
      if (attestationBuilder_ != null) {
        return attestationBuilder_.getMessageOrBuilder();
      } else {
        return attestation_ == null ?
            com.r3.sgx.enclavelethost.grpc.EpidAttestation.getDefaultInstance() : attestation_;
      }
    }
    /**
     * <code>required .proto.EpidAttestation attestation = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.r3.sgx.enclavelethost.grpc.EpidAttestation, com.r3.sgx.enclavelethost.grpc.EpidAttestation.Builder, com.r3.sgx.enclavelethost.grpc.EpidAttestationOrBuilder> 
        getAttestationFieldBuilder() {
      if (attestationBuilder_ == null) {
        attestationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.r3.sgx.enclavelethost.grpc.EpidAttestation, com.r3.sgx.enclavelethost.grpc.EpidAttestation.Builder, com.r3.sgx.enclavelethost.grpc.EpidAttestationOrBuilder>(
                getAttestation(),
                getParentForChildren(),
                isClean());
        attestation_ = null;
      }
      return attestationBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.GetEpidAttestationResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.GetEpidAttestationResponse)
  private static final com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse();
  }

  public static com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<GetEpidAttestationResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetEpidAttestationResponse>() {
    public GetEpidAttestationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetEpidAttestationResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetEpidAttestationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetEpidAttestationResponse> getParserForType() {
    return PARSER;
  }

  public com.r3.sgx.enclavelethost.grpc.GetEpidAttestationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

