// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enclavelet-host.proto

package com.r3.sgx.enclavelethost.grpc;

public interface GetEpidAttestationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetEpidAttestationRequest)
    com.google.protobuf.MessageOrBuilder {
}
