// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enclavelet-host.proto

package com.r3.sgx.enclavelethost.grpc;

public interface GetEpidAttestationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetEpidAttestationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .proto.EpidAttestation attestation = 1;</code>
   */
  boolean hasAttestation();
  /**
   * <code>required .proto.EpidAttestation attestation = 1;</code>
   */
  com.r3.sgx.enclavelethost.grpc.EpidAttestation getAttestation();
  /**
   * <code>required .proto.EpidAttestation attestation = 1;</code>
   */
  com.r3.sgx.enclavelethost.grpc.EpidAttestationOrBuilder getAttestationOrBuilder();
}
