package com.r3.conclave.enclave.internal

import org.graalvm.nativeimage.IsolateThread
import org.graalvm.nativeimage.c.function.CEntryPoint

/**
 * Static class containing constants passed to the system via build time arguments.
 * This class is initialized at build time using the nativeimage --initialize-at-built-time option and is intended
 * for use as a means of passing parameters into a project at build time. Parameters set here will be null unless
 * nativeimage is in use.
 *
 * TODO Add a properties file (generated by the gradle plugin) for the purpose of configuration (see CON-629)
 */
object NativeImageProperties {

    // Persistent map
    val enablePersistentMap = System.getProperty("com.r3.conclave.enclave.internal.NativeImageProperties.enablePersistentMap")?.toBoolean()
    val maxPersistentMapSize = System.getProperty("com.r3.conclave.enclave.internal.NativeImageProperties.maxPersistentMapSize")?.toLong()

    // Filesystem
    val inMemoryFileSystemSize = System.getProperty("com.r3.conclave.enclave.internal.NativeImageProperties.inMemoryFileSystemSize")?.toLong() ?: 0
    val persistentFileSystemSize = System.getProperty("com.r3.conclave.enclave.internal.NativeImageProperties.persistentFileSystemSize")?.toLong() ?: 0
}
