// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attestation.proto

package com.r3.sgx.core.common;

public final class Attestation {
  private Attestation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EpidHostMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EpidHostMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EpidEnclaveMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EpidEnclaveMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReportReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReportReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021attestation.proto\"U\n\017EpidHostMessage\022/" +
      "\n\022get_report_request\030\001 \001(\0132\021.GetReportRe" +
      "questH\000B\021\n\017EpidHostMessage\"W\n\022EpidEnclav" +
      "eMessage\022+\n\020get_report_reply\030\001 \001(\0132\017.Get" +
      "ReportReplyH\000B\024\n\022EpidEnclaveMessage\"7\n\020G" +
      "etReportRequest\022#\n\033quoting_enclave_targe" +
      "t_info\030\001 \002(\014\" \n\016GetReportReply\022\016\n\006report" +
      "\030\001 \002(\014B-\n\026com.r3.sgx.core.commonB\013Attest" +
      "ationP\001\242\002\003HLW"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EpidHostMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EpidHostMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EpidHostMessage_descriptor,
        new java.lang.String[] { "GetReportRequest", "EpidHostMessage", });
    internal_static_EpidEnclaveMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EpidEnclaveMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EpidEnclaveMessage_descriptor,
        new java.lang.String[] { "GetReportReply", "EpidEnclaveMessage", });
    internal_static_GetReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReportRequest_descriptor,
        new java.lang.String[] { "QuotingEnclaveTargetInfo", });
    internal_static_GetReportReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetReportReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReportReply_descriptor,
        new java.lang.String[] { "Report", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
