// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attestation.proto

package com.r3.sgx.core.common;

public interface EpidHostMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EpidHostMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .GetReportRequest get_report_request = 1;</code>
   */
  boolean hasGetReportRequest();
  /**
   * <code>optional .GetReportRequest get_report_request = 1;</code>
   */
  com.r3.sgx.core.common.GetReportRequest getGetReportRequest();
  /**
   * <code>optional .GetReportRequest get_report_request = 1;</code>
   */
  com.r3.sgx.core.common.GetReportRequestOrBuilder getGetReportRequestOrBuilder();

  public com.r3.sgx.core.common.EpidHostMessage.EpidHostMessageCase getEpidHostMessageCase();
}
