// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attestation.proto

package com.r3.sgx.core.common;

/**
 * Protobuf type {@code EpidHostMessage}
 */
public  final class EpidHostMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EpidHostMessage)
    EpidHostMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EpidHostMessage.newBuilder() to construct.
  private EpidHostMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EpidHostMessage() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EpidHostMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.r3.sgx.core.common.GetReportRequest.Builder subBuilder = null;
            if (epidHostMessageCase_ == 1) {
              subBuilder = ((com.r3.sgx.core.common.GetReportRequest) epidHostMessage_).toBuilder();
            }
            epidHostMessage_ =
                input.readMessage(com.r3.sgx.core.common.GetReportRequest.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.r3.sgx.core.common.GetReportRequest) epidHostMessage_);
              epidHostMessage_ = subBuilder.buildPartial();
            }
            epidHostMessageCase_ = 1;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.r3.sgx.core.common.Attestation.internal_static_EpidHostMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.r3.sgx.core.common.Attestation.internal_static_EpidHostMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.r3.sgx.core.common.EpidHostMessage.class, com.r3.sgx.core.common.EpidHostMessage.Builder.class);
  }

  private int bitField0_;
  private int epidHostMessageCase_ = 0;
  private java.lang.Object epidHostMessage_;
  public enum EpidHostMessageCase
      implements com.google.protobuf.Internal.EnumLite {
    GET_REPORT_REQUEST(1),
    EPIDHOSTMESSAGE_NOT_SET(0);
    private final int value;
    private EpidHostMessageCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EpidHostMessageCase valueOf(int value) {
      return forNumber(value);
    }

    public static EpidHostMessageCase forNumber(int value) {
      switch (value) {
        case 1: return GET_REPORT_REQUEST;
        case 0: return EPIDHOSTMESSAGE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public EpidHostMessageCase
  getEpidHostMessageCase() {
    return EpidHostMessageCase.forNumber(
        epidHostMessageCase_);
  }

  public static final int GET_REPORT_REQUEST_FIELD_NUMBER = 1;
  /**
   * <code>optional .GetReportRequest get_report_request = 1;</code>
   */
  public boolean hasGetReportRequest() {
    return epidHostMessageCase_ == 1;
  }
  /**
   * <code>optional .GetReportRequest get_report_request = 1;</code>
   */
  public com.r3.sgx.core.common.GetReportRequest getGetReportRequest() {
    if (epidHostMessageCase_ == 1) {
       return (com.r3.sgx.core.common.GetReportRequest) epidHostMessage_;
    }
    return com.r3.sgx.core.common.GetReportRequest.getDefaultInstance();
  }
  /**
   * <code>optional .GetReportRequest get_report_request = 1;</code>
   */
  public com.r3.sgx.core.common.GetReportRequestOrBuilder getGetReportRequestOrBuilder() {
    if (epidHostMessageCase_ == 1) {
       return (com.r3.sgx.core.common.GetReportRequest) epidHostMessage_;
    }
    return com.r3.sgx.core.common.GetReportRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (hasGetReportRequest()) {
      if (!getGetReportRequest().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (epidHostMessageCase_ == 1) {
      output.writeMessage(1, (com.r3.sgx.core.common.GetReportRequest) epidHostMessage_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (epidHostMessageCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.r3.sgx.core.common.GetReportRequest) epidHostMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.r3.sgx.core.common.EpidHostMessage)) {
      return super.equals(obj);
    }
    com.r3.sgx.core.common.EpidHostMessage other = (com.r3.sgx.core.common.EpidHostMessage) obj;

    boolean result = true;
    result = result && getEpidHostMessageCase().equals(
        other.getEpidHostMessageCase());
    if (!result) return false;
    switch (epidHostMessageCase_) {
      case 1:
        result = result && getGetReportRequest()
            .equals(other.getGetReportRequest());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (epidHostMessageCase_) {
      case 1:
        hash = (37 * hash) + GET_REPORT_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getGetReportRequest().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.r3.sgx.core.common.EpidHostMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.r3.sgx.core.common.EpidHostMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.r3.sgx.core.common.EpidHostMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.r3.sgx.core.common.EpidHostMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.r3.sgx.core.common.EpidHostMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.r3.sgx.core.common.EpidHostMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.r3.sgx.core.common.EpidHostMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.r3.sgx.core.common.EpidHostMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.r3.sgx.core.common.EpidHostMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.r3.sgx.core.common.EpidHostMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.r3.sgx.core.common.EpidHostMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.r3.sgx.core.common.EpidHostMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.r3.sgx.core.common.EpidHostMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EpidHostMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EpidHostMessage)
      com.r3.sgx.core.common.EpidHostMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.r3.sgx.core.common.Attestation.internal_static_EpidHostMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.r3.sgx.core.common.Attestation.internal_static_EpidHostMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.r3.sgx.core.common.EpidHostMessage.class, com.r3.sgx.core.common.EpidHostMessage.Builder.class);
    }

    // Construct using com.r3.sgx.core.common.EpidHostMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      epidHostMessageCase_ = 0;
      epidHostMessage_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.r3.sgx.core.common.Attestation.internal_static_EpidHostMessage_descriptor;
    }

    public com.r3.sgx.core.common.EpidHostMessage getDefaultInstanceForType() {
      return com.r3.sgx.core.common.EpidHostMessage.getDefaultInstance();
    }

    public com.r3.sgx.core.common.EpidHostMessage build() {
      com.r3.sgx.core.common.EpidHostMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.r3.sgx.core.common.EpidHostMessage buildPartial() {
      com.r3.sgx.core.common.EpidHostMessage result = new com.r3.sgx.core.common.EpidHostMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (epidHostMessageCase_ == 1) {
        if (getReportRequestBuilder_ == null) {
          result.epidHostMessage_ = epidHostMessage_;
        } else {
          result.epidHostMessage_ = getReportRequestBuilder_.build();
        }
      }
      result.bitField0_ = to_bitField0_;
      result.epidHostMessageCase_ = epidHostMessageCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.r3.sgx.core.common.EpidHostMessage) {
        return mergeFrom((com.r3.sgx.core.common.EpidHostMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.r3.sgx.core.common.EpidHostMessage other) {
      if (other == com.r3.sgx.core.common.EpidHostMessage.getDefaultInstance()) return this;
      switch (other.getEpidHostMessageCase()) {
        case GET_REPORT_REQUEST: {
          mergeGetReportRequest(other.getGetReportRequest());
          break;
        }
        case EPIDHOSTMESSAGE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (hasGetReportRequest()) {
        if (!getGetReportRequest().isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.r3.sgx.core.common.EpidHostMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.r3.sgx.core.common.EpidHostMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int epidHostMessageCase_ = 0;
    private java.lang.Object epidHostMessage_;
    public EpidHostMessageCase
        getEpidHostMessageCase() {
      return EpidHostMessageCase.forNumber(
          epidHostMessageCase_);
    }

    public Builder clearEpidHostMessage() {
      epidHostMessageCase_ = 0;
      epidHostMessage_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        com.r3.sgx.core.common.GetReportRequest, com.r3.sgx.core.common.GetReportRequest.Builder, com.r3.sgx.core.common.GetReportRequestOrBuilder> getReportRequestBuilder_;
    /**
     * <code>optional .GetReportRequest get_report_request = 1;</code>
     */
    public boolean hasGetReportRequest() {
      return epidHostMessageCase_ == 1;
    }
    /**
     * <code>optional .GetReportRequest get_report_request = 1;</code>
     */
    public com.r3.sgx.core.common.GetReportRequest getGetReportRequest() {
      if (getReportRequestBuilder_ == null) {
        if (epidHostMessageCase_ == 1) {
          return (com.r3.sgx.core.common.GetReportRequest) epidHostMessage_;
        }
        return com.r3.sgx.core.common.GetReportRequest.getDefaultInstance();
      } else {
        if (epidHostMessageCase_ == 1) {
          return getReportRequestBuilder_.getMessage();
        }
        return com.r3.sgx.core.common.GetReportRequest.getDefaultInstance();
      }
    }
    /**
     * <code>optional .GetReportRequest get_report_request = 1;</code>
     */
    public Builder setGetReportRequest(com.r3.sgx.core.common.GetReportRequest value) {
      if (getReportRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        epidHostMessage_ = value;
        onChanged();
      } else {
        getReportRequestBuilder_.setMessage(value);
      }
      epidHostMessageCase_ = 1;
      return this;
    }
    /**
     * <code>optional .GetReportRequest get_report_request = 1;</code>
     */
    public Builder setGetReportRequest(
        com.r3.sgx.core.common.GetReportRequest.Builder builderForValue) {
      if (getReportRequestBuilder_ == null) {
        epidHostMessage_ = builderForValue.build();
        onChanged();
      } else {
        getReportRequestBuilder_.setMessage(builderForValue.build());
      }
      epidHostMessageCase_ = 1;
      return this;
    }
    /**
     * <code>optional .GetReportRequest get_report_request = 1;</code>
     */
    public Builder mergeGetReportRequest(com.r3.sgx.core.common.GetReportRequest value) {
      if (getReportRequestBuilder_ == null) {
        if (epidHostMessageCase_ == 1 &&
            epidHostMessage_ != com.r3.sgx.core.common.GetReportRequest.getDefaultInstance()) {
          epidHostMessage_ = com.r3.sgx.core.common.GetReportRequest.newBuilder((com.r3.sgx.core.common.GetReportRequest) epidHostMessage_)
              .mergeFrom(value).buildPartial();
        } else {
          epidHostMessage_ = value;
        }
        onChanged();
      } else {
        if (epidHostMessageCase_ == 1) {
          getReportRequestBuilder_.mergeFrom(value);
        }
        getReportRequestBuilder_.setMessage(value);
      }
      epidHostMessageCase_ = 1;
      return this;
    }
    /**
     * <code>optional .GetReportRequest get_report_request = 1;</code>
     */
    public Builder clearGetReportRequest() {
      if (getReportRequestBuilder_ == null) {
        if (epidHostMessageCase_ == 1) {
          epidHostMessageCase_ = 0;
          epidHostMessage_ = null;
          onChanged();
        }
      } else {
        if (epidHostMessageCase_ == 1) {
          epidHostMessageCase_ = 0;
          epidHostMessage_ = null;
        }
        getReportRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .GetReportRequest get_report_request = 1;</code>
     */
    public com.r3.sgx.core.common.GetReportRequest.Builder getGetReportRequestBuilder() {
      return getGetReportRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .GetReportRequest get_report_request = 1;</code>
     */
    public com.r3.sgx.core.common.GetReportRequestOrBuilder getGetReportRequestOrBuilder() {
      if ((epidHostMessageCase_ == 1) && (getReportRequestBuilder_ != null)) {
        return getReportRequestBuilder_.getMessageOrBuilder();
      } else {
        if (epidHostMessageCase_ == 1) {
          return (com.r3.sgx.core.common.GetReportRequest) epidHostMessage_;
        }
        return com.r3.sgx.core.common.GetReportRequest.getDefaultInstance();
      }
    }
    /**
     * <code>optional .GetReportRequest get_report_request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.r3.sgx.core.common.GetReportRequest, com.r3.sgx.core.common.GetReportRequest.Builder, com.r3.sgx.core.common.GetReportRequestOrBuilder> 
        getGetReportRequestFieldBuilder() {
      if (getReportRequestBuilder_ == null) {
        if (!(epidHostMessageCase_ == 1)) {
          epidHostMessage_ = com.r3.sgx.core.common.GetReportRequest.getDefaultInstance();
        }
        getReportRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.r3.sgx.core.common.GetReportRequest, com.r3.sgx.core.common.GetReportRequest.Builder, com.r3.sgx.core.common.GetReportRequestOrBuilder>(
                (com.r3.sgx.core.common.GetReportRequest) epidHostMessage_,
                getParentForChildren(),
                isClean());
        epidHostMessage_ = null;
      }
      epidHostMessageCase_ = 1;
      onChanged();;
      return getReportRequestBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EpidHostMessage)
  }

  // @@protoc_insertion_point(class_scope:EpidHostMessage)
  private static final com.r3.sgx.core.common.EpidHostMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.r3.sgx.core.common.EpidHostMessage();
  }

  public static com.r3.sgx.core.common.EpidHostMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<EpidHostMessage>
      PARSER = new com.google.protobuf.AbstractParser<EpidHostMessage>() {
    public EpidHostMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EpidHostMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EpidHostMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EpidHostMessage> getParserForType() {
    return PARSER;
  }

  public com.r3.sgx.core.common.EpidHostMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

