// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attestation.proto

package com.r3.sgx.core.common;

public interface EpidEnclaveMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EpidEnclaveMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .GetReportReply get_report_reply = 1;</code>
   */
  boolean hasGetReportReply();
  /**
   * <code>optional .GetReportReply get_report_reply = 1;</code>
   */
  com.r3.sgx.core.common.GetReportReply getGetReportReply();
  /**
   * <code>optional .GetReportReply get_report_reply = 1;</code>
   */
  com.r3.sgx.core.common.GetReportReplyOrBuilder getGetReportReplyOrBuilder();

  public com.r3.sgx.core.common.EpidEnclaveMessage.EpidEnclaveMessageCase getEpidEnclaveMessageCase();
}
