// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: try.proto

package com.r3.sgx.core.common;

/**
 * Protobuf type {@code Exception}
 */
public  final class Exception extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Exception)
    ExceptionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Exception.newBuilder() to construct.
  private Exception(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Exception() {
    exceptionClass_ = "";
    message_ = "";
    stackTrace_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Exception(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            exceptionClass_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            message_ = bs;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              stackTrace_ = new java.util.ArrayList<com.r3.sgx.core.common.StackTraceElement>();
              mutable_bitField0_ |= 0x00000004;
            }
            stackTrace_.add(
                input.readMessage(com.r3.sgx.core.common.StackTraceElement.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        stackTrace_ = java.util.Collections.unmodifiableList(stackTrace_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.r3.sgx.core.common.TryOrFail.internal_static_Exception_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.r3.sgx.core.common.TryOrFail.internal_static_Exception_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.r3.sgx.core.common.Exception.class, com.r3.sgx.core.common.Exception.Builder.class);
  }

  private int bitField0_;
  public static final int EXCEPTIONCLASS_FIELD_NUMBER = 1;
  private volatile java.lang.Object exceptionClass_;
  /**
   * <code>required string exceptionClass = 1;</code>
   */
  public boolean hasExceptionClass() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string exceptionClass = 1;</code>
   */
  public java.lang.String getExceptionClass() {
    java.lang.Object ref = exceptionClass_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        exceptionClass_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string exceptionClass = 1;</code>
   */
  public com.google.protobuf.ByteString
      getExceptionClassBytes() {
    java.lang.Object ref = exceptionClass_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      exceptionClass_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>optional string message = 2;</code>
   */
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string message = 2;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        message_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STACKTRACE_FIELD_NUMBER = 3;
  private java.util.List<com.r3.sgx.core.common.StackTraceElement> stackTrace_;
  /**
   * <code>repeated .StackTraceElement stackTrace = 3;</code>
   */
  public java.util.List<com.r3.sgx.core.common.StackTraceElement> getStackTraceList() {
    return stackTrace_;
  }
  /**
   * <code>repeated .StackTraceElement stackTrace = 3;</code>
   */
  public java.util.List<? extends com.r3.sgx.core.common.StackTraceElementOrBuilder> 
      getStackTraceOrBuilderList() {
    return stackTrace_;
  }
  /**
   * <code>repeated .StackTraceElement stackTrace = 3;</code>
   */
  public int getStackTraceCount() {
    return stackTrace_.size();
  }
  /**
   * <code>repeated .StackTraceElement stackTrace = 3;</code>
   */
  public com.r3.sgx.core.common.StackTraceElement getStackTrace(int index) {
    return stackTrace_.get(index);
  }
  /**
   * <code>repeated .StackTraceElement stackTrace = 3;</code>
   */
  public com.r3.sgx.core.common.StackTraceElementOrBuilder getStackTraceOrBuilder(
      int index) {
    return stackTrace_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasExceptionClass()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getStackTraceCount(); i++) {
      if (!getStackTrace(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, exceptionClass_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    for (int i = 0; i < stackTrace_.size(); i++) {
      output.writeMessage(3, stackTrace_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, exceptionClass_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    for (int i = 0; i < stackTrace_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, stackTrace_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.r3.sgx.core.common.Exception)) {
      return super.equals(obj);
    }
    com.r3.sgx.core.common.Exception other = (com.r3.sgx.core.common.Exception) obj;

    boolean result = true;
    result = result && (hasExceptionClass() == other.hasExceptionClass());
    if (hasExceptionClass()) {
      result = result && getExceptionClass()
          .equals(other.getExceptionClass());
    }
    result = result && (hasMessage() == other.hasMessage());
    if (hasMessage()) {
      result = result && getMessage()
          .equals(other.getMessage());
    }
    result = result && getStackTraceList()
        .equals(other.getStackTraceList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasExceptionClass()) {
      hash = (37 * hash) + EXCEPTIONCLASS_FIELD_NUMBER;
      hash = (53 * hash) + getExceptionClass().hashCode();
    }
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    if (getStackTraceCount() > 0) {
      hash = (37 * hash) + STACKTRACE_FIELD_NUMBER;
      hash = (53 * hash) + getStackTraceList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.r3.sgx.core.common.Exception parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.r3.sgx.core.common.Exception parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.r3.sgx.core.common.Exception parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.r3.sgx.core.common.Exception parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.r3.sgx.core.common.Exception parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.r3.sgx.core.common.Exception parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.r3.sgx.core.common.Exception parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.r3.sgx.core.common.Exception parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.r3.sgx.core.common.Exception parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.r3.sgx.core.common.Exception parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.r3.sgx.core.common.Exception parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.r3.sgx.core.common.Exception parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.r3.sgx.core.common.Exception prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Exception}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Exception)
      com.r3.sgx.core.common.ExceptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.r3.sgx.core.common.TryOrFail.internal_static_Exception_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.r3.sgx.core.common.TryOrFail.internal_static_Exception_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.r3.sgx.core.common.Exception.class, com.r3.sgx.core.common.Exception.Builder.class);
    }

    // Construct using com.r3.sgx.core.common.Exception.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStackTraceFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      exceptionClass_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      message_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (stackTraceBuilder_ == null) {
        stackTrace_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        stackTraceBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.r3.sgx.core.common.TryOrFail.internal_static_Exception_descriptor;
    }

    public com.r3.sgx.core.common.Exception getDefaultInstanceForType() {
      return com.r3.sgx.core.common.Exception.getDefaultInstance();
    }

    public com.r3.sgx.core.common.Exception build() {
      com.r3.sgx.core.common.Exception result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.r3.sgx.core.common.Exception buildPartial() {
      com.r3.sgx.core.common.Exception result = new com.r3.sgx.core.common.Exception(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.exceptionClass_ = exceptionClass_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.message_ = message_;
      if (stackTraceBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          stackTrace_ = java.util.Collections.unmodifiableList(stackTrace_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.stackTrace_ = stackTrace_;
      } else {
        result.stackTrace_ = stackTraceBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.r3.sgx.core.common.Exception) {
        return mergeFrom((com.r3.sgx.core.common.Exception)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.r3.sgx.core.common.Exception other) {
      if (other == com.r3.sgx.core.common.Exception.getDefaultInstance()) return this;
      if (other.hasExceptionClass()) {
        bitField0_ |= 0x00000001;
        exceptionClass_ = other.exceptionClass_;
        onChanged();
      }
      if (other.hasMessage()) {
        bitField0_ |= 0x00000002;
        message_ = other.message_;
        onChanged();
      }
      if (stackTraceBuilder_ == null) {
        if (!other.stackTrace_.isEmpty()) {
          if (stackTrace_.isEmpty()) {
            stackTrace_ = other.stackTrace_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureStackTraceIsMutable();
            stackTrace_.addAll(other.stackTrace_);
          }
          onChanged();
        }
      } else {
        if (!other.stackTrace_.isEmpty()) {
          if (stackTraceBuilder_.isEmpty()) {
            stackTraceBuilder_.dispose();
            stackTraceBuilder_ = null;
            stackTrace_ = other.stackTrace_;
            bitField0_ = (bitField0_ & ~0x00000004);
            stackTraceBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStackTraceFieldBuilder() : null;
          } else {
            stackTraceBuilder_.addAllMessages(other.stackTrace_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasExceptionClass()) {
        return false;
      }
      for (int i = 0; i < getStackTraceCount(); i++) {
        if (!getStackTrace(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.r3.sgx.core.common.Exception parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.r3.sgx.core.common.Exception) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object exceptionClass_ = "";
    /**
     * <code>required string exceptionClass = 1;</code>
     */
    public boolean hasExceptionClass() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string exceptionClass = 1;</code>
     */
    public java.lang.String getExceptionClass() {
      java.lang.Object ref = exceptionClass_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exceptionClass_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string exceptionClass = 1;</code>
     */
    public com.google.protobuf.ByteString
        getExceptionClassBytes() {
      java.lang.Object ref = exceptionClass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exceptionClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string exceptionClass = 1;</code>
     */
    public Builder setExceptionClass(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      exceptionClass_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string exceptionClass = 1;</code>
     */
    public Builder clearExceptionClass() {
      bitField0_ = (bitField0_ & ~0x00000001);
      exceptionClass_ = getDefaultInstance().getExceptionClass();
      onChanged();
      return this;
    }
    /**
     * <code>required string exceptionClass = 1;</code>
     */
    public Builder setExceptionClassBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      exceptionClass_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>optional string message = 2;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public Builder clearMessage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      message_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.r3.sgx.core.common.StackTraceElement> stackTrace_ =
      java.util.Collections.emptyList();
    private void ensureStackTraceIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        stackTrace_ = new java.util.ArrayList<com.r3.sgx.core.common.StackTraceElement>(stackTrace_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.r3.sgx.core.common.StackTraceElement, com.r3.sgx.core.common.StackTraceElement.Builder, com.r3.sgx.core.common.StackTraceElementOrBuilder> stackTraceBuilder_;

    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public java.util.List<com.r3.sgx.core.common.StackTraceElement> getStackTraceList() {
      if (stackTraceBuilder_ == null) {
        return java.util.Collections.unmodifiableList(stackTrace_);
      } else {
        return stackTraceBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public int getStackTraceCount() {
      if (stackTraceBuilder_ == null) {
        return stackTrace_.size();
      } else {
        return stackTraceBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public com.r3.sgx.core.common.StackTraceElement getStackTrace(int index) {
      if (stackTraceBuilder_ == null) {
        return stackTrace_.get(index);
      } else {
        return stackTraceBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public Builder setStackTrace(
        int index, com.r3.sgx.core.common.StackTraceElement value) {
      if (stackTraceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStackTraceIsMutable();
        stackTrace_.set(index, value);
        onChanged();
      } else {
        stackTraceBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public Builder setStackTrace(
        int index, com.r3.sgx.core.common.StackTraceElement.Builder builderForValue) {
      if (stackTraceBuilder_ == null) {
        ensureStackTraceIsMutable();
        stackTrace_.set(index, builderForValue.build());
        onChanged();
      } else {
        stackTraceBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public Builder addStackTrace(com.r3.sgx.core.common.StackTraceElement value) {
      if (stackTraceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStackTraceIsMutable();
        stackTrace_.add(value);
        onChanged();
      } else {
        stackTraceBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public Builder addStackTrace(
        int index, com.r3.sgx.core.common.StackTraceElement value) {
      if (stackTraceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStackTraceIsMutable();
        stackTrace_.add(index, value);
        onChanged();
      } else {
        stackTraceBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public Builder addStackTrace(
        com.r3.sgx.core.common.StackTraceElement.Builder builderForValue) {
      if (stackTraceBuilder_ == null) {
        ensureStackTraceIsMutable();
        stackTrace_.add(builderForValue.build());
        onChanged();
      } else {
        stackTraceBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public Builder addStackTrace(
        int index, com.r3.sgx.core.common.StackTraceElement.Builder builderForValue) {
      if (stackTraceBuilder_ == null) {
        ensureStackTraceIsMutable();
        stackTrace_.add(index, builderForValue.build());
        onChanged();
      } else {
        stackTraceBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public Builder addAllStackTrace(
        java.lang.Iterable<? extends com.r3.sgx.core.common.StackTraceElement> values) {
      if (stackTraceBuilder_ == null) {
        ensureStackTraceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stackTrace_);
        onChanged();
      } else {
        stackTraceBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public Builder clearStackTrace() {
      if (stackTraceBuilder_ == null) {
        stackTrace_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        stackTraceBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public Builder removeStackTrace(int index) {
      if (stackTraceBuilder_ == null) {
        ensureStackTraceIsMutable();
        stackTrace_.remove(index);
        onChanged();
      } else {
        stackTraceBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public com.r3.sgx.core.common.StackTraceElement.Builder getStackTraceBuilder(
        int index) {
      return getStackTraceFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public com.r3.sgx.core.common.StackTraceElementOrBuilder getStackTraceOrBuilder(
        int index) {
      if (stackTraceBuilder_ == null) {
        return stackTrace_.get(index);  } else {
        return stackTraceBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public java.util.List<? extends com.r3.sgx.core.common.StackTraceElementOrBuilder> 
         getStackTraceOrBuilderList() {
      if (stackTraceBuilder_ != null) {
        return stackTraceBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(stackTrace_);
      }
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public com.r3.sgx.core.common.StackTraceElement.Builder addStackTraceBuilder() {
      return getStackTraceFieldBuilder().addBuilder(
          com.r3.sgx.core.common.StackTraceElement.getDefaultInstance());
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public com.r3.sgx.core.common.StackTraceElement.Builder addStackTraceBuilder(
        int index) {
      return getStackTraceFieldBuilder().addBuilder(
          index, com.r3.sgx.core.common.StackTraceElement.getDefaultInstance());
    }
    /**
     * <code>repeated .StackTraceElement stackTrace = 3;</code>
     */
    public java.util.List<com.r3.sgx.core.common.StackTraceElement.Builder> 
         getStackTraceBuilderList() {
      return getStackTraceFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.r3.sgx.core.common.StackTraceElement, com.r3.sgx.core.common.StackTraceElement.Builder, com.r3.sgx.core.common.StackTraceElementOrBuilder> 
        getStackTraceFieldBuilder() {
      if (stackTraceBuilder_ == null) {
        stackTraceBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.r3.sgx.core.common.StackTraceElement, com.r3.sgx.core.common.StackTraceElement.Builder, com.r3.sgx.core.common.StackTraceElementOrBuilder>(
                stackTrace_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        stackTrace_ = null;
      }
      return stackTraceBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Exception)
  }

  // @@protoc_insertion_point(class_scope:Exception)
  private static final com.r3.sgx.core.common.Exception DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.r3.sgx.core.common.Exception();
  }

  public static com.r3.sgx.core.common.Exception getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Exception>
      PARSER = new com.google.protobuf.AbstractParser<Exception>() {
    public Exception parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Exception(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Exception> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Exception> getParserForType() {
    return PARSER;
  }

  public com.r3.sgx.core.common.Exception getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

