// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: try.proto

package com.r3.sgx.core.common;

public interface ExceptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Exception)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string exceptionClass = 1;</code>
   */
  boolean hasExceptionClass();
  /**
   * <code>required string exceptionClass = 1;</code>
   */
  java.lang.String getExceptionClass();
  /**
   * <code>required string exceptionClass = 1;</code>
   */
  com.google.protobuf.ByteString
      getExceptionClassBytes();

  /**
   * <code>optional string message = 2;</code>
   */
  boolean hasMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .StackTraceElement stackTrace = 3;</code>
   */
  java.util.List<com.r3.sgx.core.common.StackTraceElement> 
      getStackTraceList();
  /**
   * <code>repeated .StackTraceElement stackTrace = 3;</code>
   */
  com.r3.sgx.core.common.StackTraceElement getStackTrace(int index);
  /**
   * <code>repeated .StackTraceElement stackTrace = 3;</code>
   */
  int getStackTraceCount();
  /**
   * <code>repeated .StackTraceElement stackTrace = 3;</code>
   */
  java.util.List<? extends com.r3.sgx.core.common.StackTraceElementOrBuilder> 
      getStackTraceOrBuilderList();
  /**
   * <code>repeated .StackTraceElement stackTrace = 3;</code>
   */
  com.r3.sgx.core.common.StackTraceElementOrBuilder getStackTraceOrBuilder(
      int index);
}
