// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attestation.proto

package com.r3.sgx.core.common;

public interface GetReportReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReportReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required bytes report = 1;</code>
   */
  boolean hasReport();
  /**
   * <code>required bytes report = 1;</code>
   */
  com.google.protobuf.ByteString getReport();
}
