// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attestation.proto

package com.r3.sgx.core.common;

public interface GetReportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReportRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required bytes quoting_enclave_target_info = 1;</code>
   */
  boolean hasQuotingEnclaveTargetInfo();
  /**
   * <code>required bytes quoting_enclave_target_info = 1;</code>
   */
  com.google.protobuf.ByteString getQuotingEnclaveTargetInfo();
}
