// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: try.proto

package com.r3.sgx.core.common;

public interface StackTraceElementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StackTraceElement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string className = 1;</code>
   */
  boolean hasClassName();
  /**
   * <code>required string className = 1;</code>
   */
  java.lang.String getClassName();
  /**
   * <code>required string className = 1;</code>
   */
  com.google.protobuf.ByteString
      getClassNameBytes();

  /**
   * <code>required string methodName = 2;</code>
   */
  boolean hasMethodName();
  /**
   * <code>required string methodName = 2;</code>
   */
  java.lang.String getMethodName();
  /**
   * <code>required string methodName = 2;</code>
   */
  com.google.protobuf.ByteString
      getMethodNameBytes();

  /**
   * <code>optional string fileName = 3;</code>
   */
  boolean hasFileName();
  /**
   * <code>optional string fileName = 3;</code>
   */
  java.lang.String getFileName();
  /**
   * <code>optional string fileName = 3;</code>
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>required int32 lineNumber = 4;</code>
   */
  boolean hasLineNumber();
  /**
   * <code>required int32 lineNumber = 4;</code>
   */
  int getLineNumber();
}
