// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: try.proto

package com.r3.sgx.core.common;

/**
 * Protobuf type {@code Try}
 */
public  final class Try extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Try)
    TryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Try.newBuilder() to construct.
  private Try(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Try() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Try(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            successOrFailCase_ = 1;
            successOrFail_ = input.readBytes();
            break;
          }
          case 18: {
            com.r3.sgx.core.common.Exception.Builder subBuilder = null;
            if (successOrFailCase_ == 2) {
              subBuilder = ((com.r3.sgx.core.common.Exception) successOrFail_).toBuilder();
            }
            successOrFail_ =
                input.readMessage(com.r3.sgx.core.common.Exception.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.r3.sgx.core.common.Exception) successOrFail_);
              successOrFail_ = subBuilder.buildPartial();
            }
            successOrFailCase_ = 2;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.r3.sgx.core.common.TryOrFail.internal_static_Try_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.r3.sgx.core.common.TryOrFail.internal_static_Try_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.r3.sgx.core.common.Try.class, com.r3.sgx.core.common.Try.Builder.class);
  }

  private int bitField0_;
  private int successOrFailCase_ = 0;
  private java.lang.Object successOrFail_;
  public enum SuccessOrFailCase
      implements com.google.protobuf.Internal.EnumLite {
    SUCCESS(1),
    FAILURE(2),
    SUCCESSORFAIL_NOT_SET(0);
    private final int value;
    private SuccessOrFailCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SuccessOrFailCase valueOf(int value) {
      return forNumber(value);
    }

    public static SuccessOrFailCase forNumber(int value) {
      switch (value) {
        case 1: return SUCCESS;
        case 2: return FAILURE;
        case 0: return SUCCESSORFAIL_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public SuccessOrFailCase
  getSuccessOrFailCase() {
    return SuccessOrFailCase.forNumber(
        successOrFailCase_);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  /**
   * <code>optional bytes success = 1;</code>
   */
  public boolean hasSuccess() {
    return successOrFailCase_ == 1;
  }
  /**
   * <code>optional bytes success = 1;</code>
   */
  public com.google.protobuf.ByteString getSuccess() {
    if (successOrFailCase_ == 1) {
      return (com.google.protobuf.ByteString) successOrFail_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int FAILURE_FIELD_NUMBER = 2;
  /**
   * <code>optional .Exception failure = 2;</code>
   */
  public boolean hasFailure() {
    return successOrFailCase_ == 2;
  }
  /**
   * <code>optional .Exception failure = 2;</code>
   */
  public com.r3.sgx.core.common.Exception getFailure() {
    if (successOrFailCase_ == 2) {
       return (com.r3.sgx.core.common.Exception) successOrFail_;
    }
    return com.r3.sgx.core.common.Exception.getDefaultInstance();
  }
  /**
   * <code>optional .Exception failure = 2;</code>
   */
  public com.r3.sgx.core.common.ExceptionOrBuilder getFailureOrBuilder() {
    if (successOrFailCase_ == 2) {
       return (com.r3.sgx.core.common.Exception) successOrFail_;
    }
    return com.r3.sgx.core.common.Exception.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (hasFailure()) {
      if (!getFailure().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (successOrFailCase_ == 1) {
      output.writeBytes(
          1, (com.google.protobuf.ByteString) successOrFail_);
    }
    if (successOrFailCase_ == 2) {
      output.writeMessage(2, (com.r3.sgx.core.common.Exception) successOrFail_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (successOrFailCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            1, (com.google.protobuf.ByteString) successOrFail_);
    }
    if (successOrFailCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.r3.sgx.core.common.Exception) successOrFail_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.r3.sgx.core.common.Try)) {
      return super.equals(obj);
    }
    com.r3.sgx.core.common.Try other = (com.r3.sgx.core.common.Try) obj;

    boolean result = true;
    result = result && getSuccessOrFailCase().equals(
        other.getSuccessOrFailCase());
    if (!result) return false;
    switch (successOrFailCase_) {
      case 1:
        result = result && getSuccess()
            .equals(other.getSuccess());
        break;
      case 2:
        result = result && getFailure()
            .equals(other.getFailure());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (successOrFailCase_) {
      case 1:
        hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
        hash = (53 * hash) + getSuccess().hashCode();
        break;
      case 2:
        hash = (37 * hash) + FAILURE_FIELD_NUMBER;
        hash = (53 * hash) + getFailure().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.r3.sgx.core.common.Try parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.r3.sgx.core.common.Try parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.r3.sgx.core.common.Try parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.r3.sgx.core.common.Try parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.r3.sgx.core.common.Try parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.r3.sgx.core.common.Try parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.r3.sgx.core.common.Try parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.r3.sgx.core.common.Try parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.r3.sgx.core.common.Try parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.r3.sgx.core.common.Try parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.r3.sgx.core.common.Try parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.r3.sgx.core.common.Try parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.r3.sgx.core.common.Try prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Try}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Try)
      com.r3.sgx.core.common.TryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.r3.sgx.core.common.TryOrFail.internal_static_Try_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.r3.sgx.core.common.TryOrFail.internal_static_Try_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.r3.sgx.core.common.Try.class, com.r3.sgx.core.common.Try.Builder.class);
    }

    // Construct using com.r3.sgx.core.common.Try.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      successOrFailCase_ = 0;
      successOrFail_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.r3.sgx.core.common.TryOrFail.internal_static_Try_descriptor;
    }

    public com.r3.sgx.core.common.Try getDefaultInstanceForType() {
      return com.r3.sgx.core.common.Try.getDefaultInstance();
    }

    public com.r3.sgx.core.common.Try build() {
      com.r3.sgx.core.common.Try result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.r3.sgx.core.common.Try buildPartial() {
      com.r3.sgx.core.common.Try result = new com.r3.sgx.core.common.Try(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (successOrFailCase_ == 1) {
        result.successOrFail_ = successOrFail_;
      }
      if (successOrFailCase_ == 2) {
        if (failureBuilder_ == null) {
          result.successOrFail_ = successOrFail_;
        } else {
          result.successOrFail_ = failureBuilder_.build();
        }
      }
      result.bitField0_ = to_bitField0_;
      result.successOrFailCase_ = successOrFailCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.r3.sgx.core.common.Try) {
        return mergeFrom((com.r3.sgx.core.common.Try)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.r3.sgx.core.common.Try other) {
      if (other == com.r3.sgx.core.common.Try.getDefaultInstance()) return this;
      switch (other.getSuccessOrFailCase()) {
        case SUCCESS: {
          setSuccess(other.getSuccess());
          break;
        }
        case FAILURE: {
          mergeFailure(other.getFailure());
          break;
        }
        case SUCCESSORFAIL_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (hasFailure()) {
        if (!getFailure().isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.r3.sgx.core.common.Try parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.r3.sgx.core.common.Try) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int successOrFailCase_ = 0;
    private java.lang.Object successOrFail_;
    public SuccessOrFailCase
        getSuccessOrFailCase() {
      return SuccessOrFailCase.forNumber(
          successOrFailCase_);
    }

    public Builder clearSuccessOrFail() {
      successOrFailCase_ = 0;
      successOrFail_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <code>optional bytes success = 1;</code>
     */
    public boolean hasSuccess() {
      return successOrFailCase_ == 1;
    }
    /**
     * <code>optional bytes success = 1;</code>
     */
    public com.google.protobuf.ByteString getSuccess() {
      if (successOrFailCase_ == 1) {
        return (com.google.protobuf.ByteString) successOrFail_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <code>optional bytes success = 1;</code>
     */
    public Builder setSuccess(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  successOrFailCase_ = 1;
      successOrFail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes success = 1;</code>
     */
    public Builder clearSuccess() {
      if (successOrFailCase_ == 1) {
        successOrFailCase_ = 0;
        successOrFail_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.r3.sgx.core.common.Exception, com.r3.sgx.core.common.Exception.Builder, com.r3.sgx.core.common.ExceptionOrBuilder> failureBuilder_;
    /**
     * <code>optional .Exception failure = 2;</code>
     */
    public boolean hasFailure() {
      return successOrFailCase_ == 2;
    }
    /**
     * <code>optional .Exception failure = 2;</code>
     */
    public com.r3.sgx.core.common.Exception getFailure() {
      if (failureBuilder_ == null) {
        if (successOrFailCase_ == 2) {
          return (com.r3.sgx.core.common.Exception) successOrFail_;
        }
        return com.r3.sgx.core.common.Exception.getDefaultInstance();
      } else {
        if (successOrFailCase_ == 2) {
          return failureBuilder_.getMessage();
        }
        return com.r3.sgx.core.common.Exception.getDefaultInstance();
      }
    }
    /**
     * <code>optional .Exception failure = 2;</code>
     */
    public Builder setFailure(com.r3.sgx.core.common.Exception value) {
      if (failureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        successOrFail_ = value;
        onChanged();
      } else {
        failureBuilder_.setMessage(value);
      }
      successOrFailCase_ = 2;
      return this;
    }
    /**
     * <code>optional .Exception failure = 2;</code>
     */
    public Builder setFailure(
        com.r3.sgx.core.common.Exception.Builder builderForValue) {
      if (failureBuilder_ == null) {
        successOrFail_ = builderForValue.build();
        onChanged();
      } else {
        failureBuilder_.setMessage(builderForValue.build());
      }
      successOrFailCase_ = 2;
      return this;
    }
    /**
     * <code>optional .Exception failure = 2;</code>
     */
    public Builder mergeFailure(com.r3.sgx.core.common.Exception value) {
      if (failureBuilder_ == null) {
        if (successOrFailCase_ == 2 &&
            successOrFail_ != com.r3.sgx.core.common.Exception.getDefaultInstance()) {
          successOrFail_ = com.r3.sgx.core.common.Exception.newBuilder((com.r3.sgx.core.common.Exception) successOrFail_)
              .mergeFrom(value).buildPartial();
        } else {
          successOrFail_ = value;
        }
        onChanged();
      } else {
        if (successOrFailCase_ == 2) {
          failureBuilder_.mergeFrom(value);
        }
        failureBuilder_.setMessage(value);
      }
      successOrFailCase_ = 2;
      return this;
    }
    /**
     * <code>optional .Exception failure = 2;</code>
     */
    public Builder clearFailure() {
      if (failureBuilder_ == null) {
        if (successOrFailCase_ == 2) {
          successOrFailCase_ = 0;
          successOrFail_ = null;
          onChanged();
        }
      } else {
        if (successOrFailCase_ == 2) {
          successOrFailCase_ = 0;
          successOrFail_ = null;
        }
        failureBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .Exception failure = 2;</code>
     */
    public com.r3.sgx.core.common.Exception.Builder getFailureBuilder() {
      return getFailureFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Exception failure = 2;</code>
     */
    public com.r3.sgx.core.common.ExceptionOrBuilder getFailureOrBuilder() {
      if ((successOrFailCase_ == 2) && (failureBuilder_ != null)) {
        return failureBuilder_.getMessageOrBuilder();
      } else {
        if (successOrFailCase_ == 2) {
          return (com.r3.sgx.core.common.Exception) successOrFail_;
        }
        return com.r3.sgx.core.common.Exception.getDefaultInstance();
      }
    }
    /**
     * <code>optional .Exception failure = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.r3.sgx.core.common.Exception, com.r3.sgx.core.common.Exception.Builder, com.r3.sgx.core.common.ExceptionOrBuilder> 
        getFailureFieldBuilder() {
      if (failureBuilder_ == null) {
        if (!(successOrFailCase_ == 2)) {
          successOrFail_ = com.r3.sgx.core.common.Exception.getDefaultInstance();
        }
        failureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.r3.sgx.core.common.Exception, com.r3.sgx.core.common.Exception.Builder, com.r3.sgx.core.common.ExceptionOrBuilder>(
                (com.r3.sgx.core.common.Exception) successOrFail_,
                getParentForChildren(),
                isClean());
        successOrFail_ = null;
      }
      successOrFailCase_ = 2;
      onChanged();;
      return failureBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Try)
  }

  // @@protoc_insertion_point(class_scope:Try)
  private static final com.r3.sgx.core.common.Try DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.r3.sgx.core.common.Try();
  }

  public static com.r3.sgx.core.common.Try getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Try>
      PARSER = new com.google.protobuf.AbstractParser<Try>() {
    public Try parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Try(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Try> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Try> getParserForType() {
    return PARSER;
  }

  public com.r3.sgx.core.common.Try getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

