// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: try.proto

package com.r3.sgx.core.common;

public interface TryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Try)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes success = 1;</code>
   */
  boolean hasSuccess();
  /**
   * <code>optional bytes success = 1;</code>
   */
  com.google.protobuf.ByteString getSuccess();

  /**
   * <code>optional .Exception failure = 2;</code>
   */
  boolean hasFailure();
  /**
   * <code>optional .Exception failure = 2;</code>
   */
  com.r3.sgx.core.common.Exception getFailure();
  /**
   * <code>optional .Exception failure = 2;</code>
   */
  com.r3.sgx.core.common.ExceptionOrBuilder getFailureOrBuilder();

  public com.r3.sgx.core.common.Try.SuccessOrFailCase getSuccessOrFailCase();
}
