# After interacting with the template with IntelliJ or Gradle, run this script to delete
# some autogenerated files
rm -rf template/build
rm -rf template/host/build
rm -rf template/enclave/build
rm -rf template/gradle
rm -rf template/gradlew
rm -rf template/gradlew.bat
rm -rf template/.gradle
rm -rf template/.idea
