// Inside the enclave we don't have the rtld to do symbol lookups for us. So, we must manually compute
// the name->address mappings at compile time and then let the SGX ELF loader apply the relocs itself.
//
// Because there are quite a few symbols we might want to look up, the final file is generated using a script.
// This is just a template.
//

#include <dlsym_symbols.h>

extern "C" {
void Avian_avian_Classes_acquireClassLock();
void Avian_avian_Classes_defineVMClass();
void Avian_avian_Classes_initialize();
void Avian_avian_Classes_makeString();
void Avian_avian_Classes_primitiveClass();
void Avian_avian_Classes_releaseClassLock();
void Avian_avian_Classes_resolveVMClass();
void Avian_avian_Classes_toVMClass();
void Avian_avian_Classes_toVMMethod();
void Avian_avian_Continuations_00024Continuation_handleException();
void Avian_avian_Continuations_00024Continuation_handleResult();
void Avian_avian_Continuations_callWithCurrentContinuation();
void Avian_avian_Continuations_dynamicWind2();
void Avian_avian_Machine_dumpHeap();
void Avian_avian_Machine_tryNative();
void Avian_avian_Singleton_getInt();
void Avian_avian_Singleton_getLong();
void Avian_avian_Singleton_getObject();
void Avian_avian_SystemClassLoader_00024ResourceEnumeration_nextResourceURLPrefix();
void Avian_avian_SystemClassLoader_appLoader();
void Avian_avian_SystemClassLoader_findLoadedVMClass();
void Avian_avian_SystemClassLoader_findVMClass();
void Avian_avian_SystemClassLoader_getClass();
void Avian_avian_SystemClassLoader_getPackageSource();
void Avian_avian_SystemClassLoader_resourceURLPrefix();
void Avian_avian_SystemClassLoader_startBlacklisting0();
void Avian_avian_SystemClassLoader_vmClass();
void Avian_avian_avianvmresource_Handler_00024ResourceInputStream_available();
void Avian_avian_avianvmresource_Handler_00024ResourceInputStream_close();
void Avian_avian_avianvmresource_Handler_00024ResourceInputStream_getContentLength();
void Avian_avian_avianvmresource_Handler_00024ResourceInputStream_open();
void Avian_avian_avianvmresource_Handler_00024ResourceInputStream_read__JI();
void Avian_avian_avianvmresource_Handler_00024ResourceInputStream_read__JI_3BII();
void Avian_java_lang_Class_getEnclosingClass();
void Avian_java_lang_Class_getEnclosingConstructor();
void Avian_java_lang_Class_getEnclosingMethod();
void Avian_java_lang_Class_getSuperclass();
void Avian_java_lang_Object_clone();
void Avian_java_lang_Object_getVMClass();
void Avian_java_lang_Object_hashCode();
void Avian_java_lang_Object_notify();
void Avian_java_lang_Object_notifyAll();
void Avian_java_lang_Object_toString();
void Avian_java_lang_Object_wait();
void Avian_java_lang_Runtime_exit();
void Avian_java_lang_Runtime_freeMemory();
void Avian_java_lang_Runtime_maxMemory();
void Avian_java_lang_Runtime_totalMemory();
void Avian_java_lang_invoke_LambdaMetafactory_defineUnverifiedClass();
void Avian_java_nio_FixedArrayByteBuffer_allocateFixed();
void Avian_java_util_TimeZone_getSystemGMTOffsetID();
void Avian_java_util_TimeZone_getSystemTimeZoneID();
void Avian_sun_misc_Perf_createLong();
void Avian_sun_misc_Perf_registerNatives();
void Avian_sun_misc_Unsafe_addressSize();
void Avian_sun_misc_Unsafe_allocateInstance();
void Avian_sun_misc_Unsafe_allocateMemory();
void Avian_sun_misc_Unsafe_arrayBaseOffset();
void Avian_sun_misc_Unsafe_arrayIndexScale();
void Avian_sun_misc_Unsafe_compareAndSwapInt();
void Avian_sun_misc_Unsafe_compareAndSwapLong();
void Avian_sun_misc_Unsafe_compareAndSwapObject();
void Avian_sun_misc_Unsafe_copyMemory();
void Avian_sun_misc_Unsafe_defineClass__Ljava_lang_String_2_3BIILjava_lang_ClassLoader_2Ljava_security_ProtectionDomain_2();
void Avian_sun_misc_Unsafe_ensureClassInitialized();
void Avian_sun_misc_Unsafe_freeMemory();
void Avian_sun_misc_Unsafe_getAddress__J();
void Avian_sun_misc_Unsafe_getBooleanVolatile();
void Avian_sun_misc_Unsafe_getBoolean__Ljava_lang_Object_2J();
void Avian_sun_misc_Unsafe_getByteVolatile();
void Avian_sun_misc_Unsafe_getByte__J();
void Avian_sun_misc_Unsafe_getByte__Ljava_lang_Object_2J();
void Avian_sun_misc_Unsafe_getCharVolatile();
void Avian_sun_misc_Unsafe_getChar__J();
void Avian_sun_misc_Unsafe_getChar__Ljava_lang_Object_2J();
void Avian_sun_misc_Unsafe_getDoubleVolatile();
void Avian_sun_misc_Unsafe_getDouble__J();
void Avian_sun_misc_Unsafe_getDouble__Ljava_lang_Object_2J();
void Avian_sun_misc_Unsafe_getFloatVolatile();
void Avian_sun_misc_Unsafe_getFloat__J();
void Avian_sun_misc_Unsafe_getFloat__Ljava_lang_Object_2J();
void Avian_sun_misc_Unsafe_getIntVolatile();
void Avian_sun_misc_Unsafe_getInt__J();
void Avian_sun_misc_Unsafe_getInt__Ljava_lang_Object_2J();
void Avian_sun_misc_Unsafe_getLongVolatile();
void Avian_sun_misc_Unsafe_getLong__J();
void Avian_sun_misc_Unsafe_getLong__Ljava_lang_Object_2J();
void Avian_sun_misc_Unsafe_getObject();
void Avian_sun_misc_Unsafe_getObjectVolatile();
void Avian_sun_misc_Unsafe_getShortVolatile();
void Avian_sun_misc_Unsafe_getShort__J();
void Avian_sun_misc_Unsafe_getShort__Ljava_lang_Object_2J();
void Avian_sun_misc_Unsafe_isBigEndian0();
void Avian_sun_misc_Unsafe_monitorEnter();
void Avian_sun_misc_Unsafe_monitorExit();
void Avian_sun_misc_Unsafe_objectFieldOffset();
void Avian_sun_misc_Unsafe_pageSize();
void Avian_sun_misc_Unsafe_park();
void Avian_sun_misc_Unsafe_putAddress__JJ();
void Avian_sun_misc_Unsafe_putBooleanVolatile();
void Avian_sun_misc_Unsafe_putBoolean__Ljava_lang_Object_2JZ();
void Avian_sun_misc_Unsafe_putByteVolatile();
void Avian_sun_misc_Unsafe_putByte__JB();
void Avian_sun_misc_Unsafe_putByte__Ljava_lang_Object_2JB();
void Avian_sun_misc_Unsafe_putCharVolatile();
void Avian_sun_misc_Unsafe_putChar__JC();
void Avian_sun_misc_Unsafe_putChar__Ljava_lang_Object_2JC();
void Avian_sun_misc_Unsafe_putDoubleVolatile();
void Avian_sun_misc_Unsafe_putDouble__JD();
void Avian_sun_misc_Unsafe_putDouble__Ljava_lang_Object_2JD();
void Avian_sun_misc_Unsafe_putFloatVolatile();
void Avian_sun_misc_Unsafe_putFloat__JF();
void Avian_sun_misc_Unsafe_putFloat__Ljava_lang_Object_2JF();
void Avian_sun_misc_Unsafe_putIntVolatile();
void Avian_sun_misc_Unsafe_putInt__JI();
void Avian_sun_misc_Unsafe_putInt__Ljava_lang_Object_2JI();
void Avian_sun_misc_Unsafe_putLongVolatile();
void Avian_sun_misc_Unsafe_putLong__JJ();
void Avian_sun_misc_Unsafe_putLong__Ljava_lang_Object_2JJ();
void Avian_sun_misc_Unsafe_putObject();
void Avian_sun_misc_Unsafe_putObjectVolatile();
void Avian_sun_misc_Unsafe_putOrderedInt();
void Avian_sun_misc_Unsafe_putOrderedLong();
void Avian_sun_misc_Unsafe_putOrderedObject();
void Avian_sun_misc_Unsafe_putShortVolatile();
void Avian_sun_misc_Unsafe_putShort__JS();
void Avian_sun_misc_Unsafe_putShort__Ljava_lang_Object_2JS();
void Avian_sun_misc_Unsafe_registerNatives();
void Avian_sun_misc_Unsafe_setMemory();
void Avian_sun_misc_Unsafe_staticFieldBase();
void Avian_sun_misc_Unsafe_staticFieldOffset();
void Avian_sun_misc_Unsafe_throwException();
void Avian_sun_misc_Unsafe_unalignedAccess0();
void Avian_sun_misc_Unsafe_unpark();
void JVM_Accept();
void JVM_ActiveProcessorCount();
void JVM_AllocateNewArray();
void JVM_AllocateNewObject();
void JVM_ArrayCopy();
void JVM_AssertionStatusDirectives();
void JVM_Available();
void JVM_Bind();
void JVM_CX8Field();
void JVM_ClassDepth();
void JVM_ClassLoaderDepth();
void JVM_Clone();
void JVM_Close();
void JVM_CompileClass();
void JVM_CompileClasses();
void JVM_CompilerCommand();
void JVM_Connect();
void JVM_ConstantPoolGetClassAt();
void JVM_ConstantPoolGetClassAtIfLoaded();
void JVM_ConstantPoolGetDoubleAt();
void JVM_ConstantPoolGetFieldAt();
void JVM_ConstantPoolGetFieldAtIfLoaded();
void JVM_ConstantPoolGetFloatAt();
void JVM_ConstantPoolGetIntAt();
void JVM_ConstantPoolGetLongAt();
void JVM_ConstantPoolGetMemberRefInfoAt();
void JVM_ConstantPoolGetMethodAt();
void JVM_ConstantPoolGetMethodAtIfLoaded();
void JVM_ConstantPoolGetSize();
void JVM_ConstantPoolGetStringAt();
void JVM_ConstantPoolGetUTF8At();
void JVM_CountStackFrames();
void JVM_CurrentClassLoader();
void JVM_CurrentLoadedClass();
void JVM_CurrentThread();
void JVM_CurrentTimeMillis();
void JVM_DefineClass();
void JVM_DefineClassWithSource();
void JVM_DefineClassWithSourceCond();
void JVM_DesiredAssertionStatus();
void JVM_DisableCompiler();
void JVM_DoPrivileged();
void JVM_DumpAllStacks();
void JVM_DumpThreads();
void JVM_EnableCompiler();
void JVM_Exit();
void JVM_FillInStackTrace();
void JVM_FindClassFromBootLoader();
void JVM_FindClassFromCaller();
void JVM_FindClassFromClass();
void JVM_FindClassFromClassLoader();
void JVM_FindLibraryEntry();
void JVM_FindLoadedClass();
void JVM_FindPrimitiveClass();
void JVM_FindSignal();
void JVM_FreeMemory();
void JVM_GC();
void JVM_GetAllThreads();
void JVM_GetArrayElement();
void JVM_GetArrayLength();
void JVM_GetCPClassNameUTF();
void JVM_GetCPDynamicMethodNameUTF();
void JVM_GetCPDynamicMethodSignatureUTF();
void JVM_GetCPFieldClassNameUTF();
void JVM_GetCPFieldModifiers();
void JVM_GetCPFieldNameUTF();
void JVM_GetCPFieldSignatureUTF();
void JVM_GetCPMethodClassNameUTF();
void JVM_GetCPMethodModifiers();
void JVM_GetCPMethodNameUTF();
void JVM_GetCPMethodSignatureUTF();
void JVM_GetCallerClass();
void JVM_GetClassAccessFlags();
void JVM_GetClassAnnotations();
void JVM_GetClassCPEntriesCount();
void JVM_GetClassCPTypes();
void JVM_GetClassConstantPool();
void JVM_GetClassContext();
void JVM_GetClassDeclaredConstructors();
void JVM_GetClassDeclaredFields();
void JVM_GetClassDeclaredMethods();
void JVM_GetClassFieldsCount();
void JVM_GetClassInterfaces();
void JVM_GetClassLoader();
void JVM_GetClassMethodsCount();
void JVM_GetClassModifiers();
void JVM_GetClassName();
void JVM_GetClassNameUTF();
void JVM_GetClassSignature();
void JVM_GetClassSigners();
void JVM_GetClassTypeAnnotations();
void JVM_GetComponentType();
void JVM_GetDeclaredClasses();
void JVM_GetDeclaringClass();
void JVM_GetEnclosingMethodInfo();
void JVM_GetFieldIxModifiers();
void JVM_GetFieldTypeAnnotations();
void JVM_GetHostByAddr();
void JVM_GetHostByName();
void JVM_GetHostName();
void JVM_GetInheritedAccessControlContext();
void JVM_GetInterfaceVersion();
void JVM_GetLastErrorString();
void JVM_GetManagement();
void JVM_GetMethodIxArgsSize();
void JVM_GetMethodIxByteCode();
void JVM_GetMethodIxByteCodeLength();
void JVM_GetMethodIxExceptionIndexes();
void JVM_GetMethodIxExceptionTableEntry();
void JVM_GetMethodIxExceptionTableLength();
void JVM_GetMethodIxExceptionsCount();
void JVM_GetMethodIxLocalsCount();
void JVM_GetMethodIxMaxStack();
void JVM_GetMethodIxModifiers();
void JVM_GetMethodIxNameUTF();
void JVM_GetMethodIxSignatureUTF();
void JVM_GetMethodParameters();
void JVM_GetMethodTypeAnnotations();
void JVM_GetPrimitiveArrayElement();
void JVM_GetProtectionDomain();
void JVM_GetProtoByName();
void JVM_GetResourceLookupCache();
void JVM_GetResourceLookupCacheURLs();
void JVM_GetSockName();
void JVM_GetSockOpt();
void JVM_GetStackAccessControlContext();
void JVM_GetStackTraceDepth();
void JVM_GetStackTraceElement();
void JVM_GetSystemPackage();
void JVM_GetSystemPackages();
void JVM_GetTemporaryDirectory();
void JVM_GetThreadStateNames();
void JVM_GetThreadStateValues();
void JVM_GetVersionInfo();
void JVM_Halt();
void JVM_HoldsLock();
void JVM_IHashCode();
void JVM_InitAgentProperties();
void JVM_InitProperties();
void JVM_InitializeCompiler();
void JVM_InitializeSocketLibrary();
void JVM_InternString();
void JVM_Interrupt();
void JVM_InvokeMethod();
void JVM_IsArrayClass();
void JVM_IsConstructorIx();
void JVM_IsInterface();
void JVM_IsInterrupted();
void JVM_IsNaN();
void JVM_IsPrimitiveClass();
void JVM_IsSameClassPackage();
void JVM_IsSilentCompiler();
void JVM_IsSupportedJNIVersion();
void JVM_IsThreadAlive();
void JVM_IsVMGeneratedMethodIx();
void JVM_KnownToNotExist();
void JVM_LatestUserDefinedLoader();
void JVM_Listen();
void JVM_LoadClass0();
void JVM_LoadLibrary();
void JVM_Lseek();
void JVM_MaxMemory();
void JVM_MaxObjectInspectionAge();
void JVM_MonitorNotify();
void JVM_MonitorNotifyAll();
void JVM_MonitorWait();
void JVM_NanoTime();
void JVM_NativePath();
void JVM_NewArray();
void JVM_NewInstanceFromConstructor();
void JVM_NewMultiArray();
void JVM_OnExit();
void JVM_Open();
void JVM_PrintStackTrace();
void JVM_RaiseSignal();
void JVM_RawMonitorCreate();
void JVM_RawMonitorDestroy();
void JVM_RawMonitorEnter();
void JVM_RawMonitorExit();
void JVM_Read();
void JVM_Recv();
void JVM_RecvFrom();
void JVM_RegisterSignal();
void JVM_ReleaseUTF();
void JVM_ResolveClass();
void JVM_ResumeThread();
void JVM_Send();
void JVM_SendTo();
void JVM_SetArrayElement();
void JVM_SetClassSigners();
void JVM_SetLength();
void JVM_SetNativeThreadName();
void JVM_SetPrimitiveArrayElement();
void JVM_SetProtectionDomain();
void JVM_SetSockOpt();
void JVM_SetThreadPriority();
void JVM_Sleep();
void JVM_Socket();
void JVM_SocketAvailable();
void JVM_SocketClose();
void JVM_SocketShutdown();
void JVM_StartThread();
void JVM_StopThread();
void JVM_SupportsCX8();
void JVM_SuspendThread();
void JVM_Sync();
void JVM_Timeout();
void JVM_TotalMemory();
void JVM_TraceInstructions();
void JVM_TraceMethodCalls();
void JVM_UnloadLibrary();
void JVM_Write();
void JVM_Yield();
void Java_java_io_FileDescriptor_initIDs();
void Java_java_io_FileDescriptor_sync();
void Java_java_io_FileInputStream_available0();
void Java_java_io_FileInputStream_close0();
void Java_java_io_FileInputStream_initIDs();
void Java_java_io_FileInputStream_open0();
void Java_java_io_FileInputStream_read0();
void Java_java_io_FileInputStream_readBytes();
void Java_java_io_FileInputStream_skip0();
void Java_java_io_FileOutputStream_close0();
void Java_java_io_FileOutputStream_initIDs();
void Java_java_io_FileOutputStream_open0();
void Java_java_io_FileOutputStream_write();
void Java_java_io_FileOutputStream_writeBytes();
void Java_java_io_UnixFileSystem_canonicalize0();
void Java_java_io_UnixFileSystem_checkAccess();
void Java_java_io_UnixFileSystem_createDirectory();
void Java_java_io_UnixFileSystem_createFileExclusively();
void Java_java_io_UnixFileSystem_delete0();
void Java_java_io_UnixFileSystem_getBooleanAttributes0();
void Java_java_io_UnixFileSystem_getLastModifiedTime();
void Java_java_io_UnixFileSystem_getLength();
void Java_java_io_UnixFileSystem_getSpace();
void Java_java_io_UnixFileSystem_initIDs();
void Java_java_io_UnixFileSystem_list();
void Java_java_io_UnixFileSystem_rename0();
void Java_java_io_UnixFileSystem_setLastModifiedTime();
void Java_java_io_UnixFileSystem_setPermission();
void Java_java_io_UnixFileSystem_setReadOnly();
void Java_java_lang_ClassLoader_00024NativeLibrary_find();
void Java_java_lang_ClassLoader_00024NativeLibrary_load();
void Java_java_lang_ClassLoader_00024NativeLibrary_unload();
void Java_java_lang_ClassLoader_defineClass0();
void Java_java_lang_ClassLoader_defineClass1();
void Java_java_lang_ClassLoader_defineClass2();
void Java_java_lang_ClassLoader_findBootstrapClass();
void Java_java_lang_ClassLoader_findBuiltinLib();
void Java_java_lang_ClassLoader_findLoadedClass0();
void Java_java_lang_ClassLoader_registerNatives();
void Java_java_lang_ClassLoader_resolveClass0();
void Java_java_lang_Class_forName0();
void Java_java_lang_Class_getPrimitiveClass();
void Java_java_lang_Class_isAssignableFrom();
void Java_java_lang_Class_isInstance();
void Java_java_lang_Class_registerNatives();
void Java_java_lang_Double_doubleToRawLongBits();
void Java_java_lang_Double_longBitsToDouble();
void Java_java_lang_Float_floatToRawIntBits();
void Java_java_lang_Float_intBitsToFloat();
void Java_java_lang_Object_getClass();
void Java_java_lang_Object_registerNatives();
void Java_java_lang_Package_getSystemPackage0();
void Java_java_lang_Package_getSystemPackages0();
void Java_java_lang_Runtime_availableProcessors();
void Java_java_lang_Runtime_freeMemory();
void Java_java_lang_Runtime_gc();
void Java_java_lang_Runtime_maxMemory();
void Java_java_lang_Runtime_runFinalization0();
void Java_java_lang_Runtime_totalMemory();
void Java_java_lang_Runtime_traceInstructions();
void Java_java_lang_Runtime_traceMethodCalls();
void Java_java_lang_SecurityManager_classDepth();
void Java_java_lang_SecurityManager_classLoaderDepth0();
void Java_java_lang_SecurityManager_currentClassLoader0();
void Java_java_lang_SecurityManager_currentLoadedClass0();
void Java_java_lang_SecurityManager_getClassContext();
void Java_java_lang_Shutdown_halt0();
void Java_java_lang_Shutdown_runAllFinalizers();
void Java_java_lang_StrictMath_IEEEremainder();
void Java_java_lang_StrictMath_acos();
void Java_java_lang_StrictMath_asin();
void Java_java_lang_StrictMath_atan();
void Java_java_lang_StrictMath_atan2();
void Java_java_lang_StrictMath_cbrt();
void Java_java_lang_StrictMath_cos();
void Java_java_lang_StrictMath_cosh();
void Java_java_lang_StrictMath_exp();
void Java_java_lang_StrictMath_expm1();
void Java_java_lang_StrictMath_hypot();
void Java_java_lang_StrictMath_log();
void Java_java_lang_StrictMath_log10();
void Java_java_lang_StrictMath_log1p();
void Java_java_lang_StrictMath_pow();
void Java_java_lang_StrictMath_sin();
void Java_java_lang_StrictMath_sinh();
void Java_java_lang_StrictMath_sqrt();
void Java_java_lang_StrictMath_tan();
void Java_java_lang_StrictMath_tanh();
void Java_java_lang_String_intern();
void Java_java_lang_System_identityHashCode();
void Java_java_lang_System_initProperties();
void Java_java_lang_System_mapLibraryName();
void Java_java_lang_System_registerNatives();
void Java_java_lang_System_setErr0();
void Java_java_lang_System_setIn0();
void Java_java_lang_System_setOut0();
void Java_java_lang_Thread_registerNatives();
void Java_java_lang_Throwable_fillInStackTrace();
void Java_java_lang_Throwable_getStackTraceDepth();
void Java_java_lang_Throwable_getStackTraceElement();
void Java_java_lang_reflect_Array_get();
void Java_java_lang_reflect_Array_getBoolean();
void Java_java_lang_reflect_Array_getByte();
void Java_java_lang_reflect_Array_getChar();
void Java_java_lang_reflect_Array_getDouble();
void Java_java_lang_reflect_Array_getFloat();
void Java_java_lang_reflect_Array_getInt();
void Java_java_lang_reflect_Array_getLength();
void Java_java_lang_reflect_Array_getLong();
void Java_java_lang_reflect_Array_getShort();
void Java_java_lang_reflect_Array_multiNewArray();
void Java_java_lang_reflect_Array_newArray();
void Java_java_lang_reflect_Array_set();
void Java_java_lang_reflect_Array_setBoolean();
void Java_java_lang_reflect_Array_setByte();
void Java_java_lang_reflect_Array_setChar();
void Java_java_lang_reflect_Array_setDouble();
void Java_java_lang_reflect_Array_setFloat();
void Java_java_lang_reflect_Array_setInt();
void Java_java_lang_reflect_Array_setLong();
void Java_java_lang_reflect_Array_setShort();
void Java_java_lang_reflect_Executable_getParameters0();
void Java_java_lang_reflect_Executable_getTypeAnnotationBytes0();
void Java_java_lang_reflect_Proxy_defineClass0();
void Java_java_net_InetAddress_init();
void Java_java_nio_Bits_copyFromIntArray();
void Java_java_nio_Bits_copyFromLongArray();
void Java_java_nio_Bits_copyFromShortArray();
void Java_java_nio_Bits_copyToIntArray();
void Java_java_nio_Bits_copyToLongArray();
void Java_java_nio_Bits_copyToShortArray();
void Java_java_nio_MappedByteBuffer_force0();
void Java_java_nio_MappedByteBuffer_isLoaded0();
void Java_java_nio_MappedByteBuffer_load0();
void Java_java_security_AccessController_doPrivileged__Ljava_security_PrivilegedAction_2();
void Java_java_security_AccessController_doPrivileged__Ljava_security_PrivilegedAction_2Ljava_security_AccessControlContext_2();
void Java_java_security_AccessController_doPrivileged__Ljava_security_PrivilegedExceptionAction_2();
void Java_java_security_AccessController_doPrivileged__Ljava_security_PrivilegedExceptionAction_2Ljava_security_AccessControlContext_2();
void Java_java_security_AccessController_getInheritedAccessControlContext();
void Java_java_security_AccessController_getStackAccessControlContext();
void Java_java_util_TimeZone_getSystemGMTOffsetID();
void Java_java_util_TimeZone_getSystemTimeZoneID();
void Java_java_util_concurrent_atomic_AtomicLong_VMSupportsCS8();
void Java_java_util_jar_JarFile_getMetaInfEntryNames();
void Java_java_util_logging_FileHandler_isSetUID();
void Java_java_util_prefs_FileSystemPreferences_chmod();
void Java_java_util_prefs_FileSystemPreferences_lockFile0();
void Java_java_util_prefs_FileSystemPreferences_unlockFile0();
void Java_java_util_zip_Adler32_update();
void Java_java_util_zip_Adler32_updateByteBuffer();
void Java_java_util_zip_Adler32_updateBytes();
void Java_java_util_zip_CRC32_update();
void Java_java_util_zip_CRC32_updateByteBuffer();
void Java_java_util_zip_CRC32_updateBytes();
void Java_java_util_zip_Deflater_deflateBytes();
void Java_java_util_zip_Deflater_end();
void Java_java_util_zip_Deflater_getAdler();
void Java_java_util_zip_Deflater_init();
void Java_java_util_zip_Deflater_initIDs();
void Java_java_util_zip_Deflater_reset();
void Java_java_util_zip_Deflater_setDictionary();
void Java_java_util_zip_Inflater_end();
void Java_java_util_zip_Inflater_getAdler();
void Java_java_util_zip_Inflater_inflateBytes();
void Java_java_util_zip_Inflater_init();
void Java_java_util_zip_Inflater_initIDs();
void Java_java_util_zip_Inflater_reset();
void Java_java_util_zip_Inflater_setDictionary();
void Java_java_util_zip_ZipFile_close();
void Java_java_util_zip_ZipFile_freeEntry();
void Java_java_util_zip_ZipFile_getCommentBytes();
void Java_java_util_zip_ZipFile_getEntry();
void Java_java_util_zip_ZipFile_getEntryBytes();
void Java_java_util_zip_ZipFile_getEntryCSize();
void Java_java_util_zip_ZipFile_getEntryCrc();
void Java_java_util_zip_ZipFile_getEntryFlag();
void Java_java_util_zip_ZipFile_getEntryMethod();
void Java_java_util_zip_ZipFile_getEntrySize();
void Java_java_util_zip_ZipFile_getEntryTime();
void Java_java_util_zip_ZipFile_getNextEntry();
void Java_java_util_zip_ZipFile_getTotal();
void Java_java_util_zip_ZipFile_getZipMessage();
void Java_java_util_zip_ZipFile_initIDs();
void Java_java_util_zip_ZipFile_open();
void Java_java_util_zip_ZipFile_read();
void Java_java_util_zip_ZipFile_startsWithLOC();
void Java_sun_misc_GC_maxObjectInspectionAge();
void Java_sun_misc_MessageUtils_toStderr();
void Java_sun_misc_MessageUtils_toStdout();
void Java_sun_misc_NativeSignalHandler_handle0();
void Java_sun_misc_Signal_findSignal();
void Java_sun_misc_Signal_handle0();
void Java_sun_misc_Signal_raise0();
void Java_sun_misc_URLClassPath_getLookupCacheForClassLoader();
void Java_sun_misc_URLClassPath_getLookupCacheURLs();
void Java_sun_misc_URLClassPath_knownToNotExist0();
void Java_sun_misc_VMSupport_getVMTemporaryDirectory();
void Java_sun_misc_VMSupport_initAgentProperties();
void Java_sun_misc_VM_getThreadStateValues();
void Java_sun_misc_VM_initialize();
void Java_sun_misc_VM_latestUserDefinedLoader();
void Java_sun_misc_Version_getJdkSpecialVersion();
void Java_sun_misc_Version_getJdkVersionInfo();
void Java_sun_misc_Version_getJvmSpecialVersion();
void Java_sun_misc_Version_getJvmVersionInfo();
void Java_sun_reflect_ConstantPool_getClassAt0();
void Java_sun_reflect_ConstantPool_getClassAtIfLoaded0();
void Java_sun_reflect_ConstantPool_getDoubleAt0();
void Java_sun_reflect_ConstantPool_getFieldAt0();
void Java_sun_reflect_ConstantPool_getFieldAtIfLoaded0();
void Java_sun_reflect_ConstantPool_getFloatAt0();
void Java_sun_reflect_ConstantPool_getIntAt0();
void Java_sun_reflect_ConstantPool_getLongAt0();
void Java_sun_reflect_ConstantPool_getMemberRefInfoAt0();
void Java_sun_reflect_ConstantPool_getMethodAt0();
void Java_sun_reflect_ConstantPool_getMethodAtIfLoaded0();
void Java_sun_reflect_ConstantPool_getSize0();
void Java_sun_reflect_ConstantPool_getStringAt0();
void Java_sun_reflect_ConstantPool_getUTF8At0();
void Java_sun_reflect_NativeConstructorAccessorImpl_newInstance0();
void Java_sun_reflect_NativeMethodAccessorImpl_invoke0();
void Java_sun_reflect_Reflection_getCallerClass__();
void Java_sun_reflect_Reflection_getCallerClass__I();
void Java_sun_reflect_Reflection_getClassAccessFlags();
}

DLSYM_STATIC {
    DLSYM_ADD(Avian_avian_Classes_acquireClassLock);
    DLSYM_ADD(Avian_avian_Classes_defineVMClass);
    DLSYM_ADD(Avian_avian_Classes_initialize);
    DLSYM_ADD(Avian_avian_Classes_makeString);
    DLSYM_ADD(Avian_avian_Classes_primitiveClass);
    DLSYM_ADD(Avian_avian_Classes_releaseClassLock);
    DLSYM_ADD(Avian_avian_Classes_resolveVMClass);
    DLSYM_ADD(Avian_avian_Classes_toVMClass);
    DLSYM_ADD(Avian_avian_Classes_toVMMethod);
    DLSYM_ADD(Avian_avian_Continuations_00024Continuation_handleException);
    DLSYM_ADD(Avian_avian_Continuations_00024Continuation_handleResult);
    DLSYM_ADD(Avian_avian_Continuations_callWithCurrentContinuation);
    DLSYM_ADD(Avian_avian_Continuations_dynamicWind2);
    DLSYM_ADD(Avian_avian_Machine_dumpHeap);
    DLSYM_ADD(Avian_avian_Machine_tryNative);
    DLSYM_ADD(Avian_avian_Singleton_getInt);
    DLSYM_ADD(Avian_avian_Singleton_getLong);
    DLSYM_ADD(Avian_avian_Singleton_getObject);
    DLSYM_ADD(Avian_avian_SystemClassLoader_00024ResourceEnumeration_nextResourceURLPrefix);
    DLSYM_ADD(Avian_avian_SystemClassLoader_appLoader);
    DLSYM_ADD(Avian_avian_SystemClassLoader_findLoadedVMClass);
    DLSYM_ADD(Avian_avian_SystemClassLoader_findVMClass);
    DLSYM_ADD(Avian_avian_SystemClassLoader_getClass);
    DLSYM_ADD(Avian_avian_SystemClassLoader_getPackageSource);
    DLSYM_ADD(Avian_avian_SystemClassLoader_resourceURLPrefix);
    DLSYM_ADD(Avian_avian_SystemClassLoader_startBlacklisting0);
    DLSYM_ADD(Avian_avian_SystemClassLoader_vmClass);
    DLSYM_ADD(Avian_avian_avianvmresource_Handler_00024ResourceInputStream_available);
    DLSYM_ADD(Avian_avian_avianvmresource_Handler_00024ResourceInputStream_close);
    DLSYM_ADD(Avian_avian_avianvmresource_Handler_00024ResourceInputStream_getContentLength);
    DLSYM_ADD(Avian_avian_avianvmresource_Handler_00024ResourceInputStream_open);
    DLSYM_ADD(Avian_avian_avianvmresource_Handler_00024ResourceInputStream_read__JI);
    DLSYM_ADD(Avian_avian_avianvmresource_Handler_00024ResourceInputStream_read__JI_3BII);
    DLSYM_ADD(Avian_java_lang_Class_getEnclosingClass);
    DLSYM_ADD(Avian_java_lang_Class_getEnclosingConstructor);
    DLSYM_ADD(Avian_java_lang_Class_getEnclosingMethod);
    DLSYM_ADD(Avian_java_lang_Class_getSuperclass);
    DLSYM_ADD(Avian_java_lang_Object_clone);
    DLSYM_ADD(Avian_java_lang_Object_getVMClass);
    DLSYM_ADD(Avian_java_lang_Object_hashCode);
    DLSYM_ADD(Avian_java_lang_Object_notify);
    DLSYM_ADD(Avian_java_lang_Object_notifyAll);
    DLSYM_ADD(Avian_java_lang_Object_toString);
    DLSYM_ADD(Avian_java_lang_Object_wait);
    DLSYM_ADD(Avian_java_lang_Runtime_exit);
    DLSYM_ADD(Avian_java_lang_Runtime_freeMemory);
    DLSYM_ADD(Avian_java_lang_Runtime_maxMemory);
    DLSYM_ADD(Avian_java_lang_Runtime_totalMemory);
    DLSYM_ADD(Avian_java_lang_invoke_LambdaMetafactory_defineUnverifiedClass);
    DLSYM_ADD(Avian_java_nio_FixedArrayByteBuffer_allocateFixed);
    DLSYM_ADD(Avian_java_util_TimeZone_getSystemGMTOffsetID);
    DLSYM_ADD(Avian_java_util_TimeZone_getSystemTimeZoneID);
    DLSYM_ADD(Avian_sun_misc_Perf_createLong);
    DLSYM_ADD(Avian_sun_misc_Perf_registerNatives);
    DLSYM_ADD(Avian_sun_misc_Unsafe_addressSize);
    DLSYM_ADD(Avian_sun_misc_Unsafe_allocateInstance);
    DLSYM_ADD(Avian_sun_misc_Unsafe_allocateMemory);
    DLSYM_ADD(Avian_sun_misc_Unsafe_arrayBaseOffset);
    DLSYM_ADD(Avian_sun_misc_Unsafe_arrayIndexScale);
    DLSYM_ADD(Avian_sun_misc_Unsafe_compareAndSwapInt);
    DLSYM_ADD(Avian_sun_misc_Unsafe_compareAndSwapLong);
    DLSYM_ADD(Avian_sun_misc_Unsafe_compareAndSwapObject);
    DLSYM_ADD(Avian_sun_misc_Unsafe_copyMemory);
    DLSYM_ADD(Avian_sun_misc_Unsafe_defineClass__Ljava_lang_String_2_3BIILjava_lang_ClassLoader_2Ljava_security_ProtectionDomain_2);
    DLSYM_ADD(Avian_sun_misc_Unsafe_ensureClassInitialized);
    DLSYM_ADD(Avian_sun_misc_Unsafe_freeMemory);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getAddress__J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getBooleanVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getBoolean__Ljava_lang_Object_2J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getByteVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getByte__J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getByte__Ljava_lang_Object_2J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getCharVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getChar__J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getChar__Ljava_lang_Object_2J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getDoubleVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getDouble__J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getDouble__Ljava_lang_Object_2J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getFloatVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getFloat__J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getFloat__Ljava_lang_Object_2J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getIntVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getInt__J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getInt__Ljava_lang_Object_2J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getLongVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getLong__J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getLong__Ljava_lang_Object_2J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getObject);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getObjectVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getShortVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getShort__J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_getShort__Ljava_lang_Object_2J);
    DLSYM_ADD(Avian_sun_misc_Unsafe_isBigEndian0);
    DLSYM_ADD(Avian_sun_misc_Unsafe_monitorEnter);
    DLSYM_ADD(Avian_sun_misc_Unsafe_monitorExit);
    DLSYM_ADD(Avian_sun_misc_Unsafe_objectFieldOffset);
    DLSYM_ADD(Avian_sun_misc_Unsafe_pageSize);
    DLSYM_ADD(Avian_sun_misc_Unsafe_park);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putAddress__JJ);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putBooleanVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putBoolean__Ljava_lang_Object_2JZ);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putByteVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putByte__JB);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putByte__Ljava_lang_Object_2JB);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putCharVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putChar__JC);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putChar__Ljava_lang_Object_2JC);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putDoubleVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putDouble__JD);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putDouble__Ljava_lang_Object_2JD);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putFloatVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putFloat__JF);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putFloat__Ljava_lang_Object_2JF);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putIntVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putInt__JI);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putInt__Ljava_lang_Object_2JI);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putLongVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putLong__JJ);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putLong__Ljava_lang_Object_2JJ);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putObject);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putObjectVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putOrderedInt);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putOrderedLong);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putOrderedObject);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putShortVolatile);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putShort__JS);
    DLSYM_ADD(Avian_sun_misc_Unsafe_putShort__Ljava_lang_Object_2JS);
    DLSYM_ADD(Avian_sun_misc_Unsafe_registerNatives);
    DLSYM_ADD(Avian_sun_misc_Unsafe_setMemory);
    DLSYM_ADD(Avian_sun_misc_Unsafe_staticFieldBase);
    DLSYM_ADD(Avian_sun_misc_Unsafe_staticFieldOffset);
    DLSYM_ADD(Avian_sun_misc_Unsafe_throwException);
    DLSYM_ADD(Avian_sun_misc_Unsafe_unalignedAccess0);
    DLSYM_ADD(Avian_sun_misc_Unsafe_unpark);
    DLSYM_ADD(JVM_Accept);
    DLSYM_ADD(JVM_ActiveProcessorCount);
    DLSYM_ADD(JVM_AllocateNewArray);
    DLSYM_ADD(JVM_AllocateNewObject);
    DLSYM_ADD(JVM_ArrayCopy);
    DLSYM_ADD(JVM_AssertionStatusDirectives);
    DLSYM_ADD(JVM_Available);
    DLSYM_ADD(JVM_Bind);
    DLSYM_ADD(JVM_CX8Field);
    DLSYM_ADD(JVM_ClassDepth);
    DLSYM_ADD(JVM_ClassLoaderDepth);
    DLSYM_ADD(JVM_Clone);
    DLSYM_ADD(JVM_Close);
    DLSYM_ADD(JVM_CompileClass);
    DLSYM_ADD(JVM_CompileClasses);
    DLSYM_ADD(JVM_CompilerCommand);
    DLSYM_ADD(JVM_Connect);
    DLSYM_ADD(JVM_ConstantPoolGetClassAt);
    DLSYM_ADD(JVM_ConstantPoolGetClassAtIfLoaded);
    DLSYM_ADD(JVM_ConstantPoolGetDoubleAt);
    DLSYM_ADD(JVM_ConstantPoolGetFieldAt);
    DLSYM_ADD(JVM_ConstantPoolGetFieldAtIfLoaded);
    DLSYM_ADD(JVM_ConstantPoolGetFloatAt);
    DLSYM_ADD(JVM_ConstantPoolGetIntAt);
    DLSYM_ADD(JVM_ConstantPoolGetLongAt);
    DLSYM_ADD(JVM_ConstantPoolGetMemberRefInfoAt);
    DLSYM_ADD(JVM_ConstantPoolGetMethodAt);
    DLSYM_ADD(JVM_ConstantPoolGetMethodAtIfLoaded);
    DLSYM_ADD(JVM_ConstantPoolGetSize);
    DLSYM_ADD(JVM_ConstantPoolGetStringAt);
    DLSYM_ADD(JVM_ConstantPoolGetUTF8At);
    DLSYM_ADD(JVM_CountStackFrames);
    DLSYM_ADD(JVM_CurrentClassLoader);
    DLSYM_ADD(JVM_CurrentLoadedClass);
    DLSYM_ADD(JVM_CurrentThread);
    DLSYM_ADD(JVM_CurrentTimeMillis);
    DLSYM_ADD(JVM_DefineClass);
    DLSYM_ADD(JVM_DefineClassWithSource);
    DLSYM_ADD(JVM_DefineClassWithSourceCond);
    DLSYM_ADD(JVM_DesiredAssertionStatus);
    DLSYM_ADD(JVM_DisableCompiler);
    DLSYM_ADD(JVM_DoPrivileged);
    DLSYM_ADD(JVM_DumpAllStacks);
    DLSYM_ADD(JVM_DumpThreads);
    DLSYM_ADD(JVM_EnableCompiler);
    DLSYM_ADD(JVM_Exit);
    DLSYM_ADD(JVM_FillInStackTrace);
    DLSYM_ADD(JVM_FindClassFromBootLoader);
    DLSYM_ADD(JVM_FindClassFromCaller);
    DLSYM_ADD(JVM_FindClassFromClass);
    DLSYM_ADD(JVM_FindClassFromClassLoader);
    DLSYM_ADD(JVM_FindLibraryEntry);
    DLSYM_ADD(JVM_FindLoadedClass);
    DLSYM_ADD(JVM_FindPrimitiveClass);
    DLSYM_ADD(JVM_FindSignal);
    DLSYM_ADD(JVM_FreeMemory);
    DLSYM_ADD(JVM_GC);
    DLSYM_ADD(JVM_GetAllThreads);
    DLSYM_ADD(JVM_GetArrayElement);
    DLSYM_ADD(JVM_GetArrayLength);
    DLSYM_ADD(JVM_GetCPClassNameUTF);
    DLSYM_ADD(JVM_GetCPDynamicMethodNameUTF);
    DLSYM_ADD(JVM_GetCPDynamicMethodSignatureUTF);
    DLSYM_ADD(JVM_GetCPFieldClassNameUTF);
    DLSYM_ADD(JVM_GetCPFieldModifiers);
    DLSYM_ADD(JVM_GetCPFieldNameUTF);
    DLSYM_ADD(JVM_GetCPFieldSignatureUTF);
    DLSYM_ADD(JVM_GetCPMethodClassNameUTF);
    DLSYM_ADD(JVM_GetCPMethodModifiers);
    DLSYM_ADD(JVM_GetCPMethodNameUTF);
    DLSYM_ADD(JVM_GetCPMethodSignatureUTF);
    DLSYM_ADD(JVM_GetCallerClass);
    DLSYM_ADD(JVM_GetClassAccessFlags);
    DLSYM_ADD(JVM_GetClassAnnotations);
    DLSYM_ADD(JVM_GetClassCPEntriesCount);
    DLSYM_ADD(JVM_GetClassCPTypes);
    DLSYM_ADD(JVM_GetClassConstantPool);
    DLSYM_ADD(JVM_GetClassContext);
    DLSYM_ADD(JVM_GetClassDeclaredConstructors);
    DLSYM_ADD(JVM_GetClassDeclaredFields);
    DLSYM_ADD(JVM_GetClassDeclaredMethods);
    DLSYM_ADD(JVM_GetClassFieldsCount);
    DLSYM_ADD(JVM_GetClassInterfaces);
    DLSYM_ADD(JVM_GetClassLoader);
    DLSYM_ADD(JVM_GetClassMethodsCount);
    DLSYM_ADD(JVM_GetClassModifiers);
    DLSYM_ADD(JVM_GetClassName);
    DLSYM_ADD(JVM_GetClassNameUTF);
    DLSYM_ADD(JVM_GetClassSignature);
    DLSYM_ADD(JVM_GetClassSigners);
    DLSYM_ADD(JVM_GetClassTypeAnnotations);
    DLSYM_ADD(JVM_GetComponentType);
    DLSYM_ADD(JVM_GetDeclaredClasses);
    DLSYM_ADD(JVM_GetDeclaringClass);
    DLSYM_ADD(JVM_GetEnclosingMethodInfo);
    DLSYM_ADD(JVM_GetFieldIxModifiers);
    DLSYM_ADD(JVM_GetFieldTypeAnnotations);
    DLSYM_ADD(JVM_GetHostByAddr);
    DLSYM_ADD(JVM_GetHostByName);
    DLSYM_ADD(JVM_GetHostName);
    DLSYM_ADD(JVM_GetInheritedAccessControlContext);
    DLSYM_ADD(JVM_GetInterfaceVersion);
    DLSYM_ADD(JVM_GetLastErrorString);
    DLSYM_ADD(JVM_GetManagement);
    DLSYM_ADD(JVM_GetMethodIxArgsSize);
    DLSYM_ADD(JVM_GetMethodIxByteCode);
    DLSYM_ADD(JVM_GetMethodIxByteCodeLength);
    DLSYM_ADD(JVM_GetMethodIxExceptionIndexes);
    DLSYM_ADD(JVM_GetMethodIxExceptionTableEntry);
    DLSYM_ADD(JVM_GetMethodIxExceptionTableLength);
    DLSYM_ADD(JVM_GetMethodIxExceptionsCount);
    DLSYM_ADD(JVM_GetMethodIxLocalsCount);
    DLSYM_ADD(JVM_GetMethodIxMaxStack);
    DLSYM_ADD(JVM_GetMethodIxModifiers);
    DLSYM_ADD(JVM_GetMethodIxNameUTF);
    DLSYM_ADD(JVM_GetMethodIxSignatureUTF);
    DLSYM_ADD(JVM_GetMethodParameters);
    DLSYM_ADD(JVM_GetMethodTypeAnnotations);
    DLSYM_ADD(JVM_GetPrimitiveArrayElement);
    DLSYM_ADD(JVM_GetProtectionDomain);
    DLSYM_ADD(JVM_GetProtoByName);
    DLSYM_ADD(JVM_GetResourceLookupCache);
    DLSYM_ADD(JVM_GetResourceLookupCacheURLs);
    DLSYM_ADD(JVM_GetSockName);
    DLSYM_ADD(JVM_GetSockOpt);
    DLSYM_ADD(JVM_GetStackAccessControlContext);
    DLSYM_ADD(JVM_GetStackTraceDepth);
    DLSYM_ADD(JVM_GetStackTraceElement);
    DLSYM_ADD(JVM_GetSystemPackage);
    DLSYM_ADD(JVM_GetSystemPackages);
    DLSYM_ADD(JVM_GetTemporaryDirectory);
    DLSYM_ADD(JVM_GetThreadStateNames);
    DLSYM_ADD(JVM_GetThreadStateValues);
    DLSYM_ADD(JVM_GetVersionInfo);
    DLSYM_ADD(JVM_Halt);
    DLSYM_ADD(JVM_HoldsLock);
    DLSYM_ADD(JVM_IHashCode);
    DLSYM_ADD(JVM_InitAgentProperties);
    DLSYM_ADD(JVM_InitProperties);
    DLSYM_ADD(JVM_InitializeCompiler);
    DLSYM_ADD(JVM_InitializeSocketLibrary);
    DLSYM_ADD(JVM_InternString);
    DLSYM_ADD(JVM_Interrupt);
    DLSYM_ADD(JVM_InvokeMethod);
    DLSYM_ADD(JVM_IsArrayClass);
    DLSYM_ADD(JVM_IsConstructorIx);
    DLSYM_ADD(JVM_IsInterface);
    DLSYM_ADD(JVM_IsInterrupted);
    DLSYM_ADD(JVM_IsNaN);
    DLSYM_ADD(JVM_IsPrimitiveClass);
    DLSYM_ADD(JVM_IsSameClassPackage);
    DLSYM_ADD(JVM_IsSilentCompiler);
    DLSYM_ADD(JVM_IsSupportedJNIVersion);
    DLSYM_ADD(JVM_IsThreadAlive);
    DLSYM_ADD(JVM_IsVMGeneratedMethodIx);
    DLSYM_ADD(JVM_KnownToNotExist);
    DLSYM_ADD(JVM_LatestUserDefinedLoader);
    DLSYM_ADD(JVM_Listen);
    DLSYM_ADD(JVM_LoadClass0);
    DLSYM_ADD(JVM_LoadLibrary);
    DLSYM_ADD(JVM_Lseek);
    DLSYM_ADD(JVM_MaxMemory);
    DLSYM_ADD(JVM_MaxObjectInspectionAge);
    DLSYM_ADD(JVM_MonitorNotify);
    DLSYM_ADD(JVM_MonitorNotifyAll);
    DLSYM_ADD(JVM_MonitorWait);
    DLSYM_ADD(JVM_NanoTime);
    DLSYM_ADD(JVM_NativePath);
    DLSYM_ADD(JVM_NewArray);
    DLSYM_ADD(JVM_NewInstanceFromConstructor);
    DLSYM_ADD(JVM_NewMultiArray);
    DLSYM_ADD(JVM_OnExit);
    DLSYM_ADD(JVM_Open);
    DLSYM_ADD(JVM_PrintStackTrace);
    DLSYM_ADD(JVM_RaiseSignal);
    DLSYM_ADD(JVM_RawMonitorCreate);
    DLSYM_ADD(JVM_RawMonitorDestroy);
    DLSYM_ADD(JVM_RawMonitorEnter);
    DLSYM_ADD(JVM_RawMonitorExit);
    DLSYM_ADD(JVM_Read);
    DLSYM_ADD(JVM_Recv);
    DLSYM_ADD(JVM_RecvFrom);
    DLSYM_ADD(JVM_RegisterSignal);
    DLSYM_ADD(JVM_ReleaseUTF);
    DLSYM_ADD(JVM_ResolveClass);
    DLSYM_ADD(JVM_ResumeThread);
    DLSYM_ADD(JVM_Send);
    DLSYM_ADD(JVM_SendTo);
    DLSYM_ADD(JVM_SetArrayElement);
    DLSYM_ADD(JVM_SetClassSigners);
    DLSYM_ADD(JVM_SetLength);
    DLSYM_ADD(JVM_SetNativeThreadName);
    DLSYM_ADD(JVM_SetPrimitiveArrayElement);
    DLSYM_ADD(JVM_SetProtectionDomain);
    DLSYM_ADD(JVM_SetSockOpt);
    DLSYM_ADD(JVM_SetThreadPriority);
    DLSYM_ADD(JVM_Sleep);
    DLSYM_ADD(JVM_Socket);
    DLSYM_ADD(JVM_SocketAvailable);
    DLSYM_ADD(JVM_SocketClose);
    DLSYM_ADD(JVM_SocketShutdown);
    DLSYM_ADD(JVM_StartThread);
    DLSYM_ADD(JVM_StopThread);
    DLSYM_ADD(JVM_SupportsCX8);
    DLSYM_ADD(JVM_SuspendThread);
    DLSYM_ADD(JVM_Sync);
    DLSYM_ADD(JVM_Timeout);
    DLSYM_ADD(JVM_TotalMemory);
    DLSYM_ADD(JVM_TraceInstructions);
    DLSYM_ADD(JVM_TraceMethodCalls);
    DLSYM_ADD(JVM_UnloadLibrary);
    DLSYM_ADD(JVM_Write);
    DLSYM_ADD(JVM_Yield);
    DLSYM_ADD(Java_java_io_FileDescriptor_initIDs);
    DLSYM_ADD(Java_java_io_FileDescriptor_sync);
    DLSYM_ADD(Java_java_io_FileInputStream_available0);
    DLSYM_ADD(Java_java_io_FileInputStream_close0);
    DLSYM_ADD(Java_java_io_FileInputStream_initIDs);
    DLSYM_ADD(Java_java_io_FileInputStream_open0);
    DLSYM_ADD(Java_java_io_FileInputStream_read0);
    DLSYM_ADD(Java_java_io_FileInputStream_readBytes);
    DLSYM_ADD(Java_java_io_FileInputStream_skip0);
    DLSYM_ADD(Java_java_io_FileOutputStream_close0);
    DLSYM_ADD(Java_java_io_FileOutputStream_initIDs);
    DLSYM_ADD(Java_java_io_FileOutputStream_open0);
    DLSYM_ADD(Java_java_io_FileOutputStream_write);
    DLSYM_ADD(Java_java_io_FileOutputStream_writeBytes);
    DLSYM_ADD(Java_java_io_UnixFileSystem_canonicalize0);
    DLSYM_ADD(Java_java_io_UnixFileSystem_checkAccess);
    DLSYM_ADD(Java_java_io_UnixFileSystem_createDirectory);
    DLSYM_ADD(Java_java_io_UnixFileSystem_createFileExclusively);
    DLSYM_ADD(Java_java_io_UnixFileSystem_delete0);
    DLSYM_ADD(Java_java_io_UnixFileSystem_getBooleanAttributes0);
    DLSYM_ADD(Java_java_io_UnixFileSystem_getLastModifiedTime);
    DLSYM_ADD(Java_java_io_UnixFileSystem_getLength);
    DLSYM_ADD(Java_java_io_UnixFileSystem_getSpace);
    DLSYM_ADD(Java_java_io_UnixFileSystem_initIDs);
    DLSYM_ADD(Java_java_io_UnixFileSystem_list);
    DLSYM_ADD(Java_java_io_UnixFileSystem_rename0);
    DLSYM_ADD(Java_java_io_UnixFileSystem_setLastModifiedTime);
    DLSYM_ADD(Java_java_io_UnixFileSystem_setPermission);
    DLSYM_ADD(Java_java_io_UnixFileSystem_setReadOnly);
    DLSYM_ADD(Java_java_lang_ClassLoader_00024NativeLibrary_find);
    DLSYM_ADD(Java_java_lang_ClassLoader_00024NativeLibrary_load);
    DLSYM_ADD(Java_java_lang_ClassLoader_00024NativeLibrary_unload);
    DLSYM_ADD(Java_java_lang_ClassLoader_defineClass0);
    DLSYM_ADD(Java_java_lang_ClassLoader_defineClass1);
    DLSYM_ADD(Java_java_lang_ClassLoader_defineClass2);
    DLSYM_ADD(Java_java_lang_ClassLoader_findBootstrapClass);
    DLSYM_ADD(Java_java_lang_ClassLoader_findBuiltinLib);
    DLSYM_ADD(Java_java_lang_ClassLoader_findLoadedClass0);
    DLSYM_ADD(Java_java_lang_ClassLoader_registerNatives);
    DLSYM_ADD(Java_java_lang_ClassLoader_resolveClass0);
    DLSYM_ADD(Java_java_lang_Class_forName0);
    DLSYM_ADD(Java_java_lang_Class_getPrimitiveClass);
    DLSYM_ADD(Java_java_lang_Class_isAssignableFrom);
    DLSYM_ADD(Java_java_lang_Class_isInstance);
    DLSYM_ADD(Java_java_lang_Class_registerNatives);
    DLSYM_ADD(Java_java_lang_Double_doubleToRawLongBits);
    DLSYM_ADD(Java_java_lang_Double_longBitsToDouble);
    DLSYM_ADD(Java_java_lang_Float_floatToRawIntBits);
    DLSYM_ADD(Java_java_lang_Float_intBitsToFloat);
    DLSYM_ADD(Java_java_lang_Object_getClass);
    DLSYM_ADD(Java_java_lang_Object_registerNatives);
    DLSYM_ADD(Java_java_lang_Package_getSystemPackage0);
    DLSYM_ADD(Java_java_lang_Package_getSystemPackages0);
    DLSYM_ADD(Java_java_lang_Runtime_availableProcessors);
    DLSYM_ADD(Java_java_lang_Runtime_freeMemory);
    DLSYM_ADD(Java_java_lang_Runtime_gc);
    DLSYM_ADD(Java_java_lang_Runtime_maxMemory);
    DLSYM_ADD(Java_java_lang_Runtime_runFinalization0);
    DLSYM_ADD(Java_java_lang_Runtime_totalMemory);
    DLSYM_ADD(Java_java_lang_Runtime_traceInstructions);
    DLSYM_ADD(Java_java_lang_Runtime_traceMethodCalls);
    DLSYM_ADD(Java_java_lang_SecurityManager_classDepth);
    DLSYM_ADD(Java_java_lang_SecurityManager_classLoaderDepth0);
    DLSYM_ADD(Java_java_lang_SecurityManager_currentClassLoader0);
    DLSYM_ADD(Java_java_lang_SecurityManager_currentLoadedClass0);
    DLSYM_ADD(Java_java_lang_SecurityManager_getClassContext);
    DLSYM_ADD(Java_java_lang_Shutdown_halt0);
    DLSYM_ADD(Java_java_lang_Shutdown_runAllFinalizers);
    DLSYM_ADD(Java_java_lang_StrictMath_IEEEremainder);
    DLSYM_ADD(Java_java_lang_StrictMath_acos);
    DLSYM_ADD(Java_java_lang_StrictMath_asin);
    DLSYM_ADD(Java_java_lang_StrictMath_atan);
    DLSYM_ADD(Java_java_lang_StrictMath_atan2);
    DLSYM_ADD(Java_java_lang_StrictMath_cbrt);
    DLSYM_ADD(Java_java_lang_StrictMath_cos);
    DLSYM_ADD(Java_java_lang_StrictMath_cosh);
    DLSYM_ADD(Java_java_lang_StrictMath_exp);
    DLSYM_ADD(Java_java_lang_StrictMath_expm1);
    DLSYM_ADD(Java_java_lang_StrictMath_hypot);
    DLSYM_ADD(Java_java_lang_StrictMath_log);
    DLSYM_ADD(Java_java_lang_StrictMath_log10);
    DLSYM_ADD(Java_java_lang_StrictMath_log1p);
    DLSYM_ADD(Java_java_lang_StrictMath_pow);
    DLSYM_ADD(Java_java_lang_StrictMath_sin);
    DLSYM_ADD(Java_java_lang_StrictMath_sinh);
    DLSYM_ADD(Java_java_lang_StrictMath_sqrt);
    DLSYM_ADD(Java_java_lang_StrictMath_tan);
    DLSYM_ADD(Java_java_lang_StrictMath_tanh);
    DLSYM_ADD(Java_java_lang_String_intern);
    DLSYM_ADD(Java_java_lang_System_identityHashCode);
    DLSYM_ADD(Java_java_lang_System_initProperties);
    DLSYM_ADD(Java_java_lang_System_mapLibraryName);
    DLSYM_ADD(Java_java_lang_System_registerNatives);
    DLSYM_ADD(Java_java_lang_System_setErr0);
    DLSYM_ADD(Java_java_lang_System_setIn0);
    DLSYM_ADD(Java_java_lang_System_setOut0);
    DLSYM_ADD(Java_java_lang_Thread_registerNatives);
    DLSYM_ADD(Java_java_lang_Throwable_fillInStackTrace);
    DLSYM_ADD(Java_java_lang_Throwable_getStackTraceDepth);
    DLSYM_ADD(Java_java_lang_Throwable_getStackTraceElement);
    DLSYM_ADD(Java_java_lang_reflect_Array_get);
    DLSYM_ADD(Java_java_lang_reflect_Array_getBoolean);
    DLSYM_ADD(Java_java_lang_reflect_Array_getByte);
    DLSYM_ADD(Java_java_lang_reflect_Array_getChar);
    DLSYM_ADD(Java_java_lang_reflect_Array_getDouble);
    DLSYM_ADD(Java_java_lang_reflect_Array_getFloat);
    DLSYM_ADD(Java_java_lang_reflect_Array_getInt);
    DLSYM_ADD(Java_java_lang_reflect_Array_getLength);
    DLSYM_ADD(Java_java_lang_reflect_Array_getLong);
    DLSYM_ADD(Java_java_lang_reflect_Array_getShort);
    DLSYM_ADD(Java_java_lang_reflect_Array_multiNewArray);
    DLSYM_ADD(Java_java_lang_reflect_Array_newArray);
    DLSYM_ADD(Java_java_lang_reflect_Array_set);
    DLSYM_ADD(Java_java_lang_reflect_Array_setBoolean);
    DLSYM_ADD(Java_java_lang_reflect_Array_setByte);
    DLSYM_ADD(Java_java_lang_reflect_Array_setChar);
    DLSYM_ADD(Java_java_lang_reflect_Array_setDouble);
    DLSYM_ADD(Java_java_lang_reflect_Array_setFloat);
    DLSYM_ADD(Java_java_lang_reflect_Array_setInt);
    DLSYM_ADD(Java_java_lang_reflect_Array_setLong);
    DLSYM_ADD(Java_java_lang_reflect_Array_setShort);
    DLSYM_ADD(Java_java_lang_reflect_Executable_getParameters0);
    DLSYM_ADD(Java_java_lang_reflect_Executable_getTypeAnnotationBytes0);
    DLSYM_ADD(Java_java_lang_reflect_Proxy_defineClass0);
    DLSYM_ADD(Java_java_net_InetAddress_init);
    DLSYM_ADD(Java_java_nio_Bits_copyFromIntArray);
    DLSYM_ADD(Java_java_nio_Bits_copyFromLongArray);
    DLSYM_ADD(Java_java_nio_Bits_copyFromShortArray);
    DLSYM_ADD(Java_java_nio_Bits_copyToIntArray);
    DLSYM_ADD(Java_java_nio_Bits_copyToLongArray);
    DLSYM_ADD(Java_java_nio_Bits_copyToShortArray);
    DLSYM_ADD(Java_java_nio_MappedByteBuffer_force0);
    DLSYM_ADD(Java_java_nio_MappedByteBuffer_isLoaded0);
    DLSYM_ADD(Java_java_nio_MappedByteBuffer_load0);
    DLSYM_ADD(Java_java_security_AccessController_doPrivileged__Ljava_security_PrivilegedAction_2);
    DLSYM_ADD(Java_java_security_AccessController_doPrivileged__Ljava_security_PrivilegedAction_2Ljava_security_AccessControlContext_2);
    DLSYM_ADD(Java_java_security_AccessController_doPrivileged__Ljava_security_PrivilegedExceptionAction_2);
    DLSYM_ADD(Java_java_security_AccessController_doPrivileged__Ljava_security_PrivilegedExceptionAction_2Ljava_security_AccessControlContext_2);
    DLSYM_ADD(Java_java_security_AccessController_getInheritedAccessControlContext);
    DLSYM_ADD(Java_java_security_AccessController_getStackAccessControlContext);
    DLSYM_ADD(Java_java_util_TimeZone_getSystemGMTOffsetID);
    DLSYM_ADD(Java_java_util_TimeZone_getSystemTimeZoneID);
    DLSYM_ADD(Java_java_util_concurrent_atomic_AtomicLong_VMSupportsCS8);
    DLSYM_ADD(Java_java_util_jar_JarFile_getMetaInfEntryNames);
    DLSYM_ADD(Java_java_util_logging_FileHandler_isSetUID);
    DLSYM_ADD(Java_java_util_prefs_FileSystemPreferences_chmod);
    DLSYM_ADD(Java_java_util_prefs_FileSystemPreferences_lockFile0);
    DLSYM_ADD(Java_java_util_prefs_FileSystemPreferences_unlockFile0);
    DLSYM_ADD(Java_java_util_zip_Adler32_update);
    DLSYM_ADD(Java_java_util_zip_Adler32_updateByteBuffer);
    DLSYM_ADD(Java_java_util_zip_Adler32_updateBytes);
    DLSYM_ADD(Java_java_util_zip_CRC32_update);
    DLSYM_ADD(Java_java_util_zip_CRC32_updateByteBuffer);
    DLSYM_ADD(Java_java_util_zip_CRC32_updateBytes);
    DLSYM_ADD(Java_java_util_zip_Deflater_deflateBytes);
    DLSYM_ADD(Java_java_util_zip_Deflater_end);
    DLSYM_ADD(Java_java_util_zip_Deflater_getAdler);
    DLSYM_ADD(Java_java_util_zip_Deflater_init);
    DLSYM_ADD(Java_java_util_zip_Deflater_initIDs);
    DLSYM_ADD(Java_java_util_zip_Deflater_reset);
    DLSYM_ADD(Java_java_util_zip_Deflater_setDictionary);
    DLSYM_ADD(Java_java_util_zip_Inflater_end);
    DLSYM_ADD(Java_java_util_zip_Inflater_getAdler);
    DLSYM_ADD(Java_java_util_zip_Inflater_inflateBytes);
    DLSYM_ADD(Java_java_util_zip_Inflater_init);
    DLSYM_ADD(Java_java_util_zip_Inflater_initIDs);
    DLSYM_ADD(Java_java_util_zip_Inflater_reset);
    DLSYM_ADD(Java_java_util_zip_Inflater_setDictionary);
    DLSYM_ADD(Java_java_util_zip_ZipFile_close);
    DLSYM_ADD(Java_java_util_zip_ZipFile_freeEntry);
    DLSYM_ADD(Java_java_util_zip_ZipFile_getCommentBytes);
    DLSYM_ADD(Java_java_util_zip_ZipFile_getEntry);
    DLSYM_ADD(Java_java_util_zip_ZipFile_getEntryBytes);
    DLSYM_ADD(Java_java_util_zip_ZipFile_getEntryCSize);
    DLSYM_ADD(Java_java_util_zip_ZipFile_getEntryCrc);
    DLSYM_ADD(Java_java_util_zip_ZipFile_getEntryFlag);
    DLSYM_ADD(Java_java_util_zip_ZipFile_getEntryMethod);
    DLSYM_ADD(Java_java_util_zip_ZipFile_getEntrySize);
    DLSYM_ADD(Java_java_util_zip_ZipFile_getEntryTime);
    DLSYM_ADD(Java_java_util_zip_ZipFile_getNextEntry);
    DLSYM_ADD(Java_java_util_zip_ZipFile_getTotal);
    DLSYM_ADD(Java_java_util_zip_ZipFile_getZipMessage);
    DLSYM_ADD(Java_java_util_zip_ZipFile_initIDs);
    DLSYM_ADD(Java_java_util_zip_ZipFile_open);
    DLSYM_ADD(Java_java_util_zip_ZipFile_read);
    DLSYM_ADD(Java_java_util_zip_ZipFile_startsWithLOC);
    DLSYM_ADD(Java_sun_misc_GC_maxObjectInspectionAge);
    DLSYM_ADD(Java_sun_misc_MessageUtils_toStderr);
    DLSYM_ADD(Java_sun_misc_MessageUtils_toStdout);
    DLSYM_ADD(Java_sun_misc_NativeSignalHandler_handle0);
    DLSYM_ADD(Java_sun_misc_Signal_findSignal);
    DLSYM_ADD(Java_sun_misc_Signal_handle0);
    DLSYM_ADD(Java_sun_misc_Signal_raise0);
    DLSYM_ADD(Java_sun_misc_URLClassPath_getLookupCacheForClassLoader);
    DLSYM_ADD(Java_sun_misc_URLClassPath_getLookupCacheURLs);
    DLSYM_ADD(Java_sun_misc_URLClassPath_knownToNotExist0);
    DLSYM_ADD(Java_sun_misc_VMSupport_getVMTemporaryDirectory);
    DLSYM_ADD(Java_sun_misc_VMSupport_initAgentProperties);
    DLSYM_ADD(Java_sun_misc_VM_getThreadStateValues);
    DLSYM_ADD(Java_sun_misc_VM_initialize);
    DLSYM_ADD(Java_sun_misc_VM_latestUserDefinedLoader);
    DLSYM_ADD(Java_sun_misc_Version_getJdkSpecialVersion);
    DLSYM_ADD(Java_sun_misc_Version_getJdkVersionInfo);
    DLSYM_ADD(Java_sun_misc_Version_getJvmSpecialVersion);
    DLSYM_ADD(Java_sun_misc_Version_getJvmVersionInfo);
    DLSYM_ADD(Java_sun_reflect_ConstantPool_getClassAt0);
    DLSYM_ADD(Java_sun_reflect_ConstantPool_getClassAtIfLoaded0);
    DLSYM_ADD(Java_sun_reflect_ConstantPool_getDoubleAt0);
    DLSYM_ADD(Java_sun_reflect_ConstantPool_getFieldAt0);
    DLSYM_ADD(Java_sun_reflect_ConstantPool_getFieldAtIfLoaded0);
    DLSYM_ADD(Java_sun_reflect_ConstantPool_getFloatAt0);
    DLSYM_ADD(Java_sun_reflect_ConstantPool_getIntAt0);
    DLSYM_ADD(Java_sun_reflect_ConstantPool_getLongAt0);
    DLSYM_ADD(Java_sun_reflect_ConstantPool_getMemberRefInfoAt0);
    DLSYM_ADD(Java_sun_reflect_ConstantPool_getMethodAt0);
    DLSYM_ADD(Java_sun_reflect_ConstantPool_getMethodAtIfLoaded0);
    DLSYM_ADD(Java_sun_reflect_ConstantPool_getSize0);
    DLSYM_ADD(Java_sun_reflect_ConstantPool_getStringAt0);
    DLSYM_ADD(Java_sun_reflect_ConstantPool_getUTF8At0);
    DLSYM_ADD(Java_sun_reflect_NativeConstructorAccessorImpl_newInstance0);
    DLSYM_ADD(Java_sun_reflect_NativeMethodAccessorImpl_invoke0);
    DLSYM_ADD(Java_sun_reflect_Reflection_getCallerClass__);
    DLSYM_ADD(Java_sun_reflect_Reflection_getCallerClass__I);
    DLSYM_ADD(Java_sun_reflect_Reflection_getClassAccessFlags);
}
