/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_r3_conclave_host_internal_Native */

#ifndef _Included_com_r3_conclave_host_internal_Native
#define _Included_com_r3_conclave_host_internal_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_r3_conclave_host_internal_Native
 * Method:    createEnclave
 * Signature: (Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_com_r3_conclave_host_internal_Native_createEnclave
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_r3_conclave_host_internal_Native
 * Method:    destroyEnclave
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_r3_conclave_host_internal_Native_destroyEnclave
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_r3_conclave_host_internal_Native
 * Method:    jvmECall
 * Signature: (JBB[B)V
 */
JNIEXPORT void JNICALL Java_com_r3_conclave_host_internal_Native_jvmECall
  (JNIEnv *, jclass, jlong, jbyte, jbyte, jbyteArray);

/*
 * Class:     com_r3_conclave_host_internal_Native
 * Method:    initQuote
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_r3_conclave_host_internal_Native_initQuote
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_r3_conclave_host_internal_Native
 * Method:    calcQuoteSize
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_r3_conclave_host_internal_Native_calcQuoteSize
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_r3_conclave_host_internal_Native
 * Method:    getQuote
 * Signature: ([B[B[B[B[B)V
 */
JNIEXPORT void JNICALL Java_com_r3_conclave_host_internal_Native_getQuote
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_r3_conclave_host_internal_Native
 * Method:    initQuoteDCAP
 * Signature: (Ljava/lang/String;[BZ)I
 */
JNIEXPORT jint JNICALL Java_com_r3_conclave_host_internal_Native_initQuoteDCAP
  (JNIEnv *, jclass, jstring, jbyteArray, jboolean);

/*
 * Class:     com_r3_conclave_host_internal_Native
 * Method:    calcQuoteSizeDCAP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_r3_conclave_host_internal_Native_calcQuoteSizeDCAP
  (JNIEnv *, jclass);

/*
 * Class:     com_r3_conclave_host_internal_Native
 * Method:    getQuoteDCAP
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_r3_conclave_host_internal_Native_getQuoteDCAP
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_r3_conclave_host_internal_Native
 * Method:    getQuoteCollateral
 * Signature: ([BI)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_r3_conclave_host_internal_Native_getQuoteCollateral
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_r3_conclave_host_internal_Native
 * Method:    getMetadata
 * Signature: (Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_com_r3_conclave_host_internal_Native_getMetadata
  (JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     com_r3_conclave_host_internal_Native
 * Method:    getCpuCapabilitiesSummary
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_r3_conclave_host_internal_Native_getCpuCapabilitiesSummary
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
