#!/usr/bin/env bash
set -e
# Azure CLI

SCRIPT_DIR=$(dirname $(readlink -f ${BASH_SOURCE[0]}))
VIRTUALENV_DIR=$SCRIPT_DIR/build/virtualenv-az
BUILT_FILE=$VIRTUALENV_DIR/built
if [ ! -f $BUILT_FILE ]
then
    virtualenv $VIRTUALENV_DIR
    (
        source $VIRTUALENV_DIR/bin/activate
        pip install -r $SCRIPT_DIR/requirements-az.txt
        touch $BUILT_FILE
    )
fi
source $VIRTUALENV_DIR/bin/activate
exec $VIRTUALENV_DIR/bin/az $@
