package com.r3.sgx.core.common.attestation

/**
 * A generic wrapper interface to explicitly tag data which we trust to have been generated by
 * an SGX enclave with the given measurement.
 * For example, an [AttestedOutput] can wrap an [SgxQuote] that can be attributed to a certain
 * enclave based on a remote attestation report, or a [PublicKey] that can be indirectly linked
 * to an enclave measurement via the report data field of a trusted [SgxQuote].
 */
interface AttestedOutput<T> {

    /**
     * The attested data
     */
    val data: T

    /**
     * Measurement identifying the source enclave that generated the data
     */
    val source: Measurement

}