/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_r3_conclave_host_internal_NativeShared */

#ifndef _Included_com_r3_conclave_host_internal_NativeShared
#define _Included_com_r3_conclave_host_internal_NativeShared
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_r3_conclave_host_internal_NativeShared
 * Method:    checkPlatformSupportsEnclaves
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_r3_conclave_host_internal_NativeShared_checkPlatformSupportsEnclaves
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
