# To render this docsite:
#
# 1. Install mkdocs (https://mkdocs.org) by running "pip install mkdocs"
# 2. Install mkdocs-material theme: "pip install mkdocs-material"
# 3. Run "mkdocs serve" in this directory and browse to localhost. Edits to the files will be reflected immediately.

site_name: Conclave documentation
use_directory_urls: false

nav:
  - Welcome: index.md
  - Concepts:
    - Confidential Computing: enclaves.md
    - Conclave Architecture: architecture.md
  - Development:
    - Tutorials:
        - Running your first enclave: running-hello-world.md
        - Writing your first enclave: writing-hello-world.md
        - Writing your own enclave host: writing-your-own-enclave-host.md
        - Writing a long-lived client: writing-a-long-lived-client.md
    - Design topics:
        - Conclave Mail: mail.md
        - Rapid testing and development with Mock Mode: mockmode.md
        - Maximising the security of your enclave: security.md
        - Persisting data with the Key Derivation Service: kds-detail.md
    - Reference:
        - Enclave modes: enclave-modes.md
        - Enclave constraints: constraints.md
        - Enclave persistence: persistence.md
        - Key Derivation Service configuration: kds-configuration.md
        - Threads: threads.md
        - JavaScript/Python: javascript-python.md
        - Performance: performance.md
        - Conclave Init: conclave-init.md
        - Conclave web host: conclave-web-host.md
        - DCAP: dcap.md
        - IDE Configuration: ide-configuration.md
    - API:
        - JavaDocs: api/index.html
        - Configuration options for enclaves: enclave-configuration.md
        - Key Derivation Service REST API: kds-rest-api.md
        - Migration notes: api-changes.md
        - Known issues: known-issues.md
  - Release notes: release-notes.md
  - Operations:
    - Server deployment:
        - Azure deployment: machine-setup.md
        - Non-cloud deployment: non-cloud-deployment.md
        - Intel Attestation Service: ias.md
    - Upgrades:
      - Enclave signing: signing.md
      - Renewability: renewability.md
  - FAQ: faq.md

theme:
  name: material
  logo: images/core_logo_no_shadow.svg
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
  font:
    text: Poppins

extra_css:
  - css/r3-branding.css

extra:
  social:
    - icon: fontawesome/brands/twitter-square
      link: https://twitter.com/Conclavecompute
    - icon: fontawesome/brands/discord
      link: https://discord.gg/8RhkXc5eFp
    - icon: fontawesome/brands/youtube-square
      link: https://www.youtube.com/channel/UCSZbii_Z5QXci6Sr-CvStuw
    - icon: fontawesome/brands/github
      link: https://github.com/R3Conclave

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - attr_list
  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


google_analytics:
  - 'UA-87760032-7'
  - 'auto'
